### ISSUE TITLE
Fix tests left in various HAPI test suites

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#10165]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/10162
- [ ] https://github.com/hashgraph/hedera-services/issues/9962
- [ ] https://github.com/hashgraph/hedera-services/issues/9508
- [ ] https://github.com/hashgraph/hedera-services/issues/8774
- [ ] https://github.com/hashgraph/hedera-services/issues/9502
- [ ] https://github.com/hashgraph/hedera-services/issues/8900
- [ ] https://github.com/hashgraph/hedera-services/issues/9507
```
