### ISSUE TITLE
Enable fuzzy record matching in some of Smart Contract Operations suites

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#10388]
```[tasklist]
### Tasks
- [ ] Enable fuzzy record matching for DelegateCallOperationSuite (1 test)
- [ ] Enable fuzzy record matching for ExtCodeCopyOperationSuite (1 test)
- [ ] Enable fuzzy record matching for ExtCodeHashOperationSuite (1 test)
- [ ] Enable fuzzy record matching for ExtCodeSizeOperationSuite (1 test)
- [ ] Enable fuzzy record matching for GlobalPropertiesSuite (4 tests)
- [ ] Enable fuzzy record matching for PrngSeedOperationSuite (3 tests)
```
