### ISSUE TITLE
Enable fuzzy record matching in Smart Contract Records and some of the Operations suites

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#10387]
The following Smart Contract suites have all of their tests passing, we need to enable fuzzy record matching for them:

```[tasklist]
### Tasks
- [ ] Enable fuzzy record matching for LogsSuite (5 tests)
- [ ] Enable fuzzy record matching for RecordsSuite (2 tests)
- [ ] Enable fuzzy record matching for BalanceOperationSuite (1 test)
- [ ] Enable fuzzy record matching for CallCodeOperationSuite: (1 test)
- [ ] Enable fuzzy record matching for CallOperationSuite (2 tests)
```
