### ISSUE TITLE
EVM v0.50 version support

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#10408]
Provide initial base support for a new EVM version in modularized to capture Cancun changes.
This should cover the structures needed to support the upgrade and would create no op implementations of needed override classes.

Future tickets will populate the various features in the modularized code.
```[tasklist]
### Tasks
- [ ] MCOPY opcode support (EIP-1153)
- [ ] TLOAD/TSTORE opcode support (EIP-5656)
- [ ] Beacon Block Root Precompile support (EIP-4788)
- [ ] Shared Blob Transactions support (EIP-4844): transaction format
- [ ] Shared Blob Transactions support (EIP-4844): BLOBHASH opcode
- [ ] Shared Blob Transactions support (EIP-4844): KZG precompile
```

**Comment by lukelee-sl** [comment]
Finished elsewhere
