### ISSUE TITLE
Add support for running modular code in the performance networks

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/hedera-services#10458]
## Description

Performance testing of the new modularized Hedera Services application code will require changes to the production docker image definitions, the `com.hedera.node.app.ServicesMain` class, and the Node Management Tools. 

```[tasklist]
### Tasks
- [ ]  https://github.com/hashgraph/hedera-services/issues/10450
- [ ] https://github.com/hashgraph/hedera-services/issues/10459
- [ ] https://github.com/swirlds/swirlds-docker/issues/874
```
