### ISSUE TITLE
Enable fuzzy record matching for Smart Contracts suites for HAPI operations

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#10704]
```[tasklist]
### Tasks
- [ ] Enable fuzzy record matching for ContractCallSuite (46 tests)
- [ ] Enable fuzzy record matching for ContractCallLocalSuite (9 tests)
- [ ] Enable fuzzy record matching for ContractCreateSuite (20 tests)
- [ ] Enable fuzzy record matching for ContractDeleteSuite (10 tests)
- [ ] Enable fuzzy record matching for ContractGetBytecodeSuite (3 tests)
- [ ] Enable fuzzy record matching for ContractGetInfoSuite (3 tests)
- [ ] Enable fuzzy record matching for ContractUpdateSuite (13 tests)
```
