### ISSUE TITLE
Enable fuzzy record matching for the rest of Smart Contract suites (Part 1)

### ISSUE THREAD

**Issue by mustafauzunn** [hashgraph/hedera-services#10728]
```[tasklist]
### Tasks
- [x] https://github.com/hashgraph/hedera-services/issues/10894
- [ ] https://github.com/hashgraph/hedera-services/issues/10895
- [ ] https://github.com/hashgraph/hedera-services/issues/10896
- [ ] https://github.com/hashgraph/hedera-services/issues/10871
- [ ] https://github.com/hashgraph/hedera-services/issues/10863
- [ ] https://github.com/hashgraph/hedera-services/issues/10869
- [ ] https://github.com/hashgraph/hedera-services/issues/10854
- [ ] https://github.com/hashgraph/hedera-services/issues/10851
- [ ] https://github.com/hashgraph/hedera-services/issues/10800
- [ ] https://github.com/hashgraph/hedera-services/issues/10803
- [ ] https://github.com/hashgraph/hedera-services/issues/10853
```
