### ISSUE TITLE
Enable fuzzy record matching for the rest of Smart Contract suites (Part 2) 

### ISSUE THREAD

**Issue by mustafauzunn** [hashgraph/hedera-services#10729]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/10802
- [ ] https://github.com/hashgraph/hedera-services/issues/10942
- [ ] https://github.com/hashgraph/hedera-services/issues/10805
- [ ] https://github.com/hashgraph/hedera-services/issues/10860
- [ ] https://github.com/hashgraph/hedera-services/issues/10974
- [ ] https://github.com/hashgraph/hedera-services/issues/10835
- [ ] https://github.com/hashgraph/hedera-services/issues/10855
- [ ] https://github.com/hashgraph/hedera-services/issues/10976
- [ ] https://github.com/hashgraph/hedera-services/issues/10905
- [ ] https://github.com/hashgraph/hedera-services/issues/10858
- [ ] https://github.com/hashgraph/hedera-services/issues/10969
```

**Comment by georgi-l95** [comment]
Closing as all items are ready.
