### ISSUE TITLE
Public Merkle API

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#10988]
The main goal of this epic is turn state-related code into a library that can later be used by the Block Node.  Besides that we need to change our Merkle Tree structure and standardize the Platform state nodes into one of three types:
- singleton
- queue
- key-value storage

```[tasklist]
### Merkle Tree Cleanup
- [ ] https://github.com/hashgraph/hedera-services/issues/11770
- [ ] https://github.com/hashgraph/hedera-services/issues/11767
- [ ] https://github.com/hashgraph/hedera-services/issues/12277
- [ ] https://github.com/hashgraph/hedera-services/issues/11765
- [ ] https://github.com/hashgraph/hedera-services/issues/11772
- [ ] https://github.com/hashgraph/hedera-services/issues/13084
- [ ] https://github.com/hashgraph/hedera-services/issues/13690
- [ ] https://github.com/hashgraph/hedera-services/issues/13691
- [ ] https://github.com/hashgraph/hedera-services/issues/13124
- [ ] https://github.com/hashgraph/hedera-services/issues/13270
- [ ] https://github.com/hashgraph/hedera-services/issues/14220
- [ ] https://github.com/hashgraph/hedera-services/issues/14230
- [ ] https://github.com/hashgraph/hedera-services/issues/11771
- [ ] https://github.com/hashgraph/hedera-services/issues/11773
- [ ] https://github.com/hashgraph/hedera-services/issues/13274
- [ ] https://github.com/hashgraph/hedera-services/issues/13781
- [ ] https://github.com/hashgraph/hedera-services/issues/13802
- [ ] https://github.com/hashgraph/hedera-services/issues/13891
- [ ] https://github.com/hashgraph/hedera-services/issues/14196
- [ ] https://github.com/hashgraph/hedera-services/issues/14098
- [ ] https://github.com/hashgraph/hedera-services/issues/14099
- [ ] https://github.com/hashgraph/hedera-services/issues/14294
- [ ] https://github.com/hashgraph/hedera-services/issues/14355
- [ ] https://github.com/hashgraph/hedera-services/issues/14773
- [ ] https://github.com/hashgraph/hedera-services/issues/14797
```

```[tasklist]
### States API
- [ ] https://github.com/hashgraph/hedera-services/issues/11774
- [ ] https://github.com/hashgraph/hedera-services/issues/13125
- [ ] https://github.com/hashgraph/hedera-services/issues/13240
- [ ] https://github.com/hashgraph/hedera-services/issues/13241
- [ ] https://github.com/hashgraph/hedera-services/issues/13242
- [ ] https://github.com/hashgraph/hedera-services/issues/13246
- [ ] Determine how to handle hashing for the FCQueue considering the state proof use case
```

**Comment by imalygin** [comment]
@cody-littley proposed to do a refactoring of `PlatformState` - https://www.notion.so/swirldslabs/Proposed-Platform-State-Structure-d37ae2c018f94b81ac884745ca4ee022

I'm going to update this epic accordingly
