### ISSUE TITLE
Gradle Build Enhancements

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/hedera-services#11230]
## Description

This epic level issue tracks all outstanding Gradle build enhancements, changes, and bug fixes.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/14255
- [ ] https://github.com/hashgraph/hedera-services/issues/13836
- [ ] https://github.com/hashgraph/hedera-services/issues/13324
- [ ] https://github.com/hashgraph/hedera-services/issues/11657
- [ ] https://github.com/hashgraph/hedera-services/issues/13505
- [ ] https://github.com/hashgraph/hedera-services/issues/11568
- [ ] https://github.com/hashgraph/hedera-services/issues/13655
- [ ] https://github.com/hashgraph/hedera-services/issues/11564
- [ ] https://github.com/hashgraph/hedera-services/issues/13753
- [ ] https://github.com/hashgraph/hedera-services/issues/11900
- [ ] https://github.com/hashgraph/hedera-services/issues/11569
- [ ] https://github.com/hashgraph/hedera-services/issues/12798
- [ ] https://github.com/hashgraph/hedera-services/issues/11570
- [ ] https://github.com/hashgraph/hedera-services/issues/11565
- [ ] https://github.com/hashgraph/hedera-services/issues/11237
- [ ] https://github.com/hashgraph/hedera-services/issues/11659
- [ ] https://github.com/hashgraph/hedera-services/issues/13023
- [ ] https://github.com/hashgraph/hedera-services/issues/11236
- [ ] https://github.com/hashgraph/hedera-services/issues/11574
- [ ] https://github.com/hashgraph/hedera-services/issues/11863
- [ ] https://github.com/hashgraph/hedera-services/issues/11658
- [ ] https://github.com/hashgraph/hedera-services/issues/11573
```

**Comment by david-bakin-sl** [comment]
@nathanklick, @jasperpotts  - I'd like to make sure that Solidity support - for smart contract production code and test code - doesn't drop off the list.  I know the priority is low relative to these other tasks. (It was on the initial roadmap for gradle build improvements.)

**Comment by rbair23** [comment]
I'd like to add moving protobuf definitions to consensus node / mirror node repos as appropriate

**Comment by jjohannes** [comment]
@david-bakin-sl thanks. That is indeed still on the list, but was not yet transferred into an issue here. It is now. If there is any more context on the topic (other issues or docs) please feel free to add more information to this issue: https://github.com/hashgraph/hedera-services/issues/11657

**Comment by jjohannes** [comment]
@rbair23 I created https://github.com/hashgraph/hedera-services/issues/11658
I miss some context here and do not know how things can/should move from/to where.
Please feel free to fill that issue with concrete content. Or we can use it to discuss options. (cc @jasperpotts)
