### ISSUE TITLE
Open Review / Open Source

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#113]
- [ ] Platform Code Restructure ( Open JDK Java 12, and other refactoring)
- [ ] Platform Technical Debt & Unit test coverage - Node count agnostic
- [ ] Platform Technical Debt & Unit test coverage - Event & Record Stream running hash in state
- [ ] Code Audit
