### ISSUE TITLE
Hedera Services Improvements Bugs & Minor features

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#114]
- [ ] Entity Expiration / Renewal
- [ ] Query on Signed State
- [ ] TLS on GRPC
- [ ] HAPI Review & Cleanup
- [ ] Atomic Fee Schedule / Exchange Rate Update
- [ ] Hedera Services Cleanup & Documentation
