### ISSUE TITLE
Fix flaky HAPI tests

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#11414]
A prerequisite for switching to the modular code is making the HAPI tests required in CI. But some of the tests are flaky and need to be stabilized before we can do that:

- [ ] `AutoAccountCreationSuite.transferHbarsToEVMAddressAlias`: https://github.com/hashgraph/hedera-services/actions/runs/7811332921/job/21306442129?pr=11412
- [ ] `MixedOpsRestartTest.restartMixedOps`: https://github.com/hashgraph/hedera-services/actions/runs/7811332921/job/21306442880?pr=11412 and https://github.com/hashgraph/hedera-services/actions/runs/7834024326/job/21376670879?pr=11456
- [ ]  [canUpdateMultipliersDynamically2](https://scans.gradle.com/s/aqn3hrmer5shg/tests/task/:test-clients:hapiTestMisc/details/com.hedera.services.bdd.suites.fees.CongestionPricingSuite/canUpdateMultipliersDynamically2)
- [ ] `ScheduleCreateSpecs`:https://scans.gradle.com/s/dpaqdl24wryui/tests/task/:test-clients:eet/details/EndToEndTests/schedule()%5B1%5D%5B19%5D?top-execution=1
- [ ] `recordStreamValidation`: https://scans.gradle.com/s/q33hobypnfwlg
```[tasklist]
### Tasks
```
