### ISSUE TITLE
Add additional test coverage for custom fees during transfer

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#11581]
Custom fees can be set to a token during token creation. Then when we perform a transfer on the token, fee related business logic is executed for proper payment of the fee collector. With this package we would add additional test coverage to validate all cases behave correctly.

**Total: ~100 test cases after discussions with QA team**

**Additional work package items:**
- [Deleted smart contract can be called successfully](https://github.com/hashgraph/hedera-services/issues/11664)
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/11761
- [ ] https://github.com/hashgraph/hedera-services/issues/11793
- [x] https://github.com/hashgraph/hedera-services/issues/11832
- [x] https://github.com/hashgraph/hedera-services/issues/11833
```
