### ISSUE TITLE
Convert to proxy wiring

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#12143]
```[tasklist]
###
- [ ] https://github.com/hashgraph/hedera-services/issues/12128
- [ ] https://github.com/hashgraph/hedera-services/issues/12131
- [ ] https://github.com/hashgraph/hedera-services/issues/12144
- [ ] https://github.com/hashgraph/hedera-services/issues/12133
- [ ] https://github.com/hashgraph/hedera-services/issues/12184
- [ ] https://github.com/hashgraph/hedera-services/issues/12186
- [ ] Use proxy wiring for `EventStreamManagerWiring`
- [ ] https://github.com/hashgraph/hedera-services/issues/12146
- [ ] Use proxy wiring for `EventWindowManagerWiring`
- [ ] https://github.com/hashgraph/hedera-services/issues/12148
```

**Comment by cody-littley** [comment]
I've moved these tasks into the [Turtle Lite](https://github.com/hashgraph/hedera-services/issues/12178) epic.
