### ISSUE TITLE
HIP-540: Change Or Remove Existing Keys From A Token

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#12156]
Link to the HIP: https://hips.hedera.com/hip/hip-540

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/12157
- [ ] https://github.com/hashgraph/hedera-services/issues/12158
- [ ] https://github.com/hashgraph/hedera-services/issues/12159
- [ ] https://github.com/hashgraph/hedera-services/issues/12160
- [ ] https://github.com/hashgraph/hedera-services/issues/12270
- [ ] https://github.com/hashgraph/hedera-services/issues/12395
- [ ] https://github.com/hashgraph/hedera-services/issues/12682
```
