### ISSUE TITLE
Validate and Add any missing `pureChecks()` in Crypto and Token handlers

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#12711]
Validate the basic fields are set correctly in `pureChecks` in all token and crypto handlers. Add any if they are missing.

- [x] CryptoAddLiveHashHandler – nothing needed; not supported
- [x] CryptoApproveAllowanceHandler – nothing needed (see comment below about operatorId)
- [x] #12714
- [x] CryptoDeleteAllowanceHandler – ~~if nftAllowances is not null, non-null checks on all contained allowances and sub-objects~~ nothing needed
- [x] CryptoDeleteHandler – ~~if transferAccountID is not null, transferAccountID is valid; if deleteAccountID is not null, deleteAccountID is valid~~ nothing needed
- [x] CryptoDeleteLiveHashHandler – nothing needed; not supported
- [x] #12715
- [x] CryptoGetAccountInfoHandler – ~~could check that accountID is valid, but `validate()` depends on looking up the account object from state??~~ nothing needed (see comment about checking null below)
- [x] CryptoGetAccountRecordsHandler – ~~could check that accountID is valid, but `validate()` depends on looking up the account object from state??~~ nothing needed (see comment about checking null below)
- [x] CryptoGetLiveHashHandler – nothing needed; not supported
- [x] CryptoGetStakersHandler – nothing needed; not supported
- [x] #12817
- [x] CryptoUpdateHandler – nothing needed
- [x] TokenAccountWipeHandler – ~~#12758~~ nothing needed
- [x] TokenAssociateToAccountHandler – ~~issue #12758 – if accountID is not null, accountID is valid~~ nothing needed
- [x] TokenBurnHandler – ~~issue #12758 – if tokenID is not null, tokenID is valid; serialNums is not null~~ nothing needed
- [x] TokenCreateHandler – nothing needed
- [x] TokenDeleteHandler – ~~if tokenID is not null, tokenID is valid~~ nothing needed
- [x] TokenDissociateFromAccountHandler – ~~if accountID is not null, accountID is valid; if tokens is not null, all contained tokenIDs are valid~~ nothing needed
- [x] TokenFeeScheduleUpdateHandler – ~~if accountID is not null, accountID is valid;~~ if customFees is not null, all contained custom fees are valid~~ nothing needed
- [x] TokenFreezeAccountHandler – ~~if accountID is not null, accountID is valid; if tokenID is not null, tokenID is valid~~ nothing needed
- [x] TokenGetAccountNftInfosHandler – nothing needed; not supported
- [x] TokenGetInfoHandler – ~~could check that tokenID is valid, but `validate()` depends on looking up the account object from state??~~ nothing needed (see comment about checking null below)
- [x] TokenGetNftInfoHandler – ~~could check that tokenID is valid, but `validate()` depends on looking up the account object from state??~~ nothing needed (see comment about checking null below)
- [x] TokenGetNftInfosHandler – nothing needed; not supported
- [x] TokenGrantKycToAccountHandler – ~~if tokenID is not null, tokenID is valid; if accountID is not null, accountID is valid~~ nothing needed
- [x] TokenHandlers – wrapper for all crypto/token handlers, no pure checks here. Nothing needed.
- [x] TokenMintHandler – nothing needed
- [x] TokenPauseHandler – ~~if tokenID is not null, tokenID is valid~~ nothing needed
- [x] TokenRevokeKycFromAccountHandler – ~~if tokenID is not null, tokenID is valid; if accountID is not null, accountID is valid~~ nothing needed
- [x] TokenUnfreezeAccountHandler – ~~if tokenID is not null, tokenID is valid; if accountID is not null, accountID is valid~~ nothing needed
- [x] #12816
- [x] TokenUpdateNftsHandler – ~~if tokenID is not null, tokenID is valid; if serialNumbers is not null, all contained serial numbers are > 0; if serialNumbers is not null, all contained objects are not null; if metadata is not null, do we need to check the size of this field?? Or is that done from config or a store somewhere?~~ nothing needed (see comment about validateSemantics below)

**Comment by thomas-swirlds-labs** [comment]
Some of the queries can depend on state so maybe `pureChecks` is not relevant to queries at all? 
However - `CryptoGetAccountBalanceHandler` for example is a QueryHandler so it doesn't have a `pureChecks` method but in this case we could also just add the new checks into the validate method?

**Comment by Neeharika-Sompalli** [comment]
> CryptoApproveAllowanceHandler – only one question, everything else seems fine: we could move [this](https://github.com/hashgraph/hedera-services/blob/7056eeacde38b686114b7bf253baf0a7a5c9bf7a/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoApproveAllowanceHandler.java#L163) calculation of the operatorId to pureChecks, but it seems that we correctly reject in prehandle for this case. Should we move it?

I think its fine to not move it.

>  FinalizeChildRecordHandler – special handler; shouldn't receive client requests??
>  FinalizeParentRecordHandler – special handler; shouldn't receive client requests??
Nothing should be done here. Removed from the list



> TokenUpdateNftsHandler – if tokenID is not null, tokenID is valid; if serialNumbers is not null, all contained serial numbers are > 0; if metadata is not null, do we need to check the size of this field?? Or is that done from config or a store somewhere?

PureChecks should not involve any configuration to check. So, checking size of metadata field is not needed. It will be done in validateSemantics

> TokenGetInfoHandler – could check that tokenID is valid, but validate() depends on looking up the token object from state??
> TokenGetNftInfoHandler – could check that tokenID is valid, but validate() depends on looking up the token object from state??

We should just see if TokenId  tokenNum > 0. The real validation from state will be done later

**Comment by mhess-swl** [comment]
Today we clarified as a team that we only want to make changes to avoid null pointer exceptions in the pure checks, but otherwise match mono behavior. Accordingly, I'll go through and update the requirements in the ticket description.

**Comment by mhess-swl** [comment]
> We should just see if TokenId tokenNum > 0. The real validation from state will be done later

Update on this, we'll only check that TokenId is not null
