### ISSUE TITLE
Add Design docs needed in all Services

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#13076]
Add Design docs needed for all services

- [ ]Add Design docs needed in Token Service
- [ ] Add missing Javadocs in Crypto Service
- [ ] Add missing Javadocs in Network Admin Service
- [ ] Add missing Javadocs in Consensus Service
- [ ] Add missing Javadocs in Smart Contract Service
- [ ] Add missing Javadocs in File Service
- [ ] Add missing Javadocs in Schedule service
