### ISSUE TITLE
HIP-904: Implement pending state for airdrop purposes

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#13113]
### Problem

In order to integrate airdrop functionality in Hedera ([HIP-904](https://hips.hedera.com/hip/hip-904)), we need to have a special pending state, which would keep track of all incoming airdrops that are related to tokens and receivers with missing auto association capabilities (e.g. no available auto association slots or maxAutoAssociations=0).

This state should be serialisable and available after node upgrades or restarts.

It shouldn't be able to directly commit changes into the persistent state. This would be only possible if a successful token claim operation is performed.

### Solution

Define a new state structure using the defined protobuf types for airdrops. Provide a mechanism for interacting with it and thoroughly test it.

Follow this [design doc](https://github.com/hashgraph/hedera-services/pull/12792) for more details.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/13938
- [ ] https://github.com/hashgraph/hedera-services/issues/13939
- [ ] https://github.com/hashgraph/hedera-services/issues/13940
```

```[tasklist]
### Definition of done
- [x] Implement pending state related changes
- [x] Test the pending state in isolation using unit and xtests
```

**Comment by vtronkov** [comment]
Approved and merged into the feature branch: https://github.com/hashgraph/hedera-services/pull/13566
