### ISSUE TITLE
TSS  Library

### ISSUE THREAD

**Issue by litt3** [hashgraph/hedera-services#13316]
### Proposal
https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/docs/proposals/TSS-Library/TSS-Library.md

```[tasklist]
### Pre-Project
- [ ] #13865
- [ ] https://github.com/hashgraph/hedera-services/issues/13236
- [ ] https://github.com/hashgraph/hedera-services/issues/13358
- [ ] https://github.com/hashgraph/hedera-services/issues/13161
- [ ] https://github.com/hashgraph/hedera-services/issues/14096
- [ ] https://github.com/hashgraph/hedera-services/issues/14149
```

```[tasklist]
### Stage 1
- [ ] https://github.com/hashgraph/hedera-services/issues/15216
```

```[tasklist]
### Stage 2
- [ ] https://github.com/hashgraph/hedera-services/issues/15405
- [ ] https://github.com/hashgraph/hedera-services/issues/16022
- [ ] https://github.com/hashgraph/hedera-services/issues/16060
- [ ] https://github.com/hashgraph/hedera-services/issues/16103
- [ ] https://github.com/hashgraph/hedera-services/issues/16104
- [ ] https://github.com/hashgraph/hedera-services/issues/15211
- [ ] https://github.com/hashgraph/hedera-services/issues/15495
- [ ] https://github.com/hashgraph/hedera-services/issues/16438
- [ ] https://github.com/hashgraph/hedera-services/issues/16393
- [ ] https://github.com/hashgraph/hedera-services/issues/16481
- [ ] https://github.com/hashgraph/hedera-services/issues/15506
- [ ] https://github.com/hashgraph/hedera-services/issues/16096
- [ ] https://github.com/hashgraph/hedera-services/issues/16136
- [ ] https://github.com/hashgraph/hedera-services/issues/16489
- [ ] https://github.com/hashgraph/hedera-services/issues/16601
- [ ] https://github.com/hashgraph/hedera-services/issues/16673
- [ ] https://github.com/hashgraph/hedera-services/issues/16814
- [ ] https://github.com/hashgraph/hedera-services/issues/16815
- [ ] https://github.com/hashgraph/hedera-services/issues/16898
- [ ] https://github.com/hashgraph/hedera-services/issues/14146
```

```[tasklist]
### Serialization
- [ ] https://github.com/hashgraph/hedera-services/issues/16680
- [ ] https://github.com/hashgraph/hedera-services/issues/16681
- [ ] https://github.com/hashgraph/hedera-services/issues/16688
- [ ] https://github.com/hashgraph/hedera-services/issues/16682
- [ ] https://github.com/hashgraph/hedera-services/issues/16683
- [ ] https://github.com/hashgraph/hedera-services/issues/16684
- [ ] https://github.com/hashgraph/hedera-services/issues/16685
- [ ] https://github.com/hashgraph/hedera-services/issues/17145
```

```[tasklist]
### Investigation & Misc
- [ ] https://github.com/hashgraph/hedera-services/issues/14134
- [ ] https://github.com/hashgraph/hedera-services/issues/14390
- [ ] https://github.com/hashgraph/hedera-services/issues/15169
- [ ] https://github.com/hashgraph/hedera-services/issues/15507
- [ ] https://github.com/hashgraph/hedera-services/issues/15505
- [ ] https://github.com/hashgraph/hedera-services/issues/16046
- [ ] https://github.com/hashgraph/hedera-services/issues/15555
- [ ] https://github.com/hashgraph/hedera-services/issues/16377
- [ ] https://github.com/hashgraph/hedera-services/issues/14135
- [ ] https://github.com/hashgraph/hedera-services/issues/16674
- [ ] https://github.com/hashgraph/hedera-services/issues/15508
- [ ] https://github.com/hashgraph/hedera-services/issues/14142
- [ ] https://github.com/hashgraph/hedera-services/issues/14145
- [ ] https://github.com/hashgraph/hedera-services/issues/16606
```

```[tasklist]
### Closed as invalid or replaced
- [ ] https://github.com/hashgraph/hedera-services/issues/14195
- [ ] https://github.com/hashgraph/hedera-services/issues/15026
- [ ] https://github.com/hashgraph/hedera-services/issues/14139
- [ ] https://github.com/hashgraph/hedera-services/issues/13327
- [ ] https://github.com/hashgraph/hedera-services/issues/15496
```
### This Epic depends on
- https://github.com/hashgraph/hedera-services/issues/13324
- https://github.com/hashgraph/hedera-services/issues/14100

### This Epic is prerequisite of 
- https://github.com/hashgraph/hedera-services/issues/13315

**Comment by poulok** [comment]
OBE
