### ISSUE TITLE
Replace `XTest` by using `@HapiTest` with an embedded `HederaNetwork`

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#13425]
### Problem

As a developer I often want to validate pure application logic, especially workflow logic that integrates many components. 

Running a `@HapiTest` against a subprocess network does, of course, accomplish this.

However, 
  1. The time spent starting a subprocess network dominates the time of running a single `@HapiTest`.
  2. Even the very short time-to-finality of such a network adds up to hours when running thousands of `@HapiTest`s.
  3. Debugging a node running in a separate JVM is much more cumbersome than debugging a JUnit test process.
  4. It is impossible to generate deterministic record streams from a live network; so regression tests need fuzzy-matching.

The `xtest` module tried to address these pain points, but has the massive shortcoming that we cannot reuse `HapiSpec` DSL and our existing library of `@HapiTest`s. 

This issue is to take the basic ideas from `xtest`, discard that module, and instead allow `@HapiTest`'s to be run against a `Hedera` network "embedded" in the JUnit test process.

### Solution

:one: **Encapsulate `@HapiTest` network operations**
- [x] #13539
- [x] Extend the existing subprocess-based `HederaNetwork` to implement the new APIs via gRPC stubs managed by `HapiClients`.
- [x] Add a `RemoteHederaNetwork` implementation that can target tests at a remote network (i.e. not managed subprocesses).
- [x] Instantiate all `HapiSpec`'s with a target `HederaNetwork`; eliminate any use of the `nodes` spec property that does not consist of instantiating a `SubProcessHederaNetwork` or `RemoteHederaNetwork`.
- [x] Change all `HapiTxnOp#callToUse()` and `HapiQueryOp#submitWith()` implementations to invoke the appropriate `HederaNetwork` API on the spec's target network.

:two: **Implement the `EmbeddedHederaNetwork`**
- [x] #13537
- [x] #13543
- [x] #13542
- [x] Create an `EmbeddedHederaNetwork` that instantiates a `FakePlatform`, `FakeServicesRegistry`, and `FakeHederaState`; then uses then to instantiate and initialize a single `Hedera` that will represent every node in the network.
- [x] Implement the `HederaNetwork` APIs to directly call `{Ingest/PreHandle/Handle/Query}Workflow`s as appropriate with synchronous responses.
- [x] Register a `testEmbedded` task that configures the `SharedNetworkSessionListener` to set the global `SHARED_NETWORK` to be an `EmbeddedHederaNetwork` instead of a `SubProcessHederaNetwork`.

**Comment by david-bakin-sl** [comment]
I'm all for this but the drawback of focusing on the HAPI DSL is that it is _completely undocumented_. We really really really need a guide for HAPI - both so that you can read and develop tests, and that you can know what and how to extend it.

I'm thinking something similar to the [protobuf language guide](https://protobuf.dev/programming-guides/proto3/) - one large page describing how you do things and then each thing you do, with some examples.
