### ISSUE TITLE
Add declarative entity creation to `@HapiTest`s

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#13565]
### Problem

Our existing `@HapiTest`s suffer from a huge amount of boilerplate devoted to creating entities.

This at minimum distracts from the main purpose of the test; and in many cases, obscures it almost entirely.

### Solution

Use the JUnit Jupiter extension APIs to support declarative entity creation in three ways:
- [ ] Via `static` field injection (`BeforeAllCallback` API)
- [ ] Via instance field injection (`BeforeEachCallback` API)
- [ ] Via `@Test` method parameter injection (`ParameterResolver` API)

This will require a few steps.
  - [ ] Defining Java types that represent entities that should be pre-created before a `@HapiTest` runs.
  - [ ] Using JUnit `AnnotationSupport` to inject instances of these types into test classes and instances.
  - [ ] Using a `ParameterResolver` to inject instances into `@Test` methods.
  - [ ] Having an appropriate extension that will bind a `List<SpecEntity>` of all declarative dependencies to the thread before invoking a `HapiSpec` factory.
  - [ ] Updating `HapiSpec.run()` to ensure all required entities are created on the target network and "linked" to its registry before executing the user's operations.
  - [ ] Adding `@HapiTest` DSL that works in terms of Java instances instead of `HapiSpecRegistry` names.
