### ISSUE TITLE
HIP-904: Finalize TokenAirdrop configurations and add integration tests

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#13659]
Following #13658 we need to add final configurations for the new `TokenAirdrop` transaction type, as well as provide integration tests coverage.

More details and information about the transaction type can be found in this [design doc](https://github.com/hashgraph/hedera-services/pull/12794).

```[tasklist]
### Tasks
- [x] Add needed changes in `feeSchedule` files and `ThroughputLimits` for the new operation
- [x] Add the operation in the ApiPermissionConfig settings
- [x] Implement integration tests for the acceptance tests from the design doc
```

```[tasklist]
### Definition of done
- [x] Define the needed changes for the `TokenAirdrop` transaction in `feeSchedules`
- [x] Add the TokenAirdrop operation in all resources needed for throttle
- [x] Add the TokenAirdrop operation in the ApiPermissionConfig
- [x] Provide integration tests for the acceptance tests from the design doc
```

**Comment by vtronkov** [comment]
Completed in https://github.com/hashgraph/hedera-services/pull/14279
