### ISSUE TITLE
HIP-904: TokenCancelAirdrop configurations and integration tests

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#13684]
Following https://github.com/hashgraph/hedera-services/issues/13683 we need to add final configurations for the new `TokenCancelAirdrop` transaction type, as well as provide integration tests coverage.

More details and information about the transaction type can be found in [this design doc](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/docs/design/services/token-service/airdrops/token-cancel-airdrop.md).

```[tasklist]
### Tasks
- [x] Add needed changes in `feeSchedule` files, throttle `ThroughputLimits` and `ApiPermissionConfig` for the new operation
- [x] Implement integration tests for the acceptance tests from the design doc and any additional cases from the test plan
```
```[tasklist]
### Definition of done
- [x] Define the needed changes for the `TokenCancelAirdrop` transaction in `feeSchedules`, throttle definitions and API permissions config
- [x] Provide integration tests for the acceptance tests from the design doc
```
