### ISSUE TITLE
Submit PBJ payloads

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#13709]
### Intro
Before transaction/payloads get put into an event that is being created, we currently create and self-serializable instances that contain the PBJ version of the payload. These self-serializable payloads are submitted to the EventCreator. This ticket is to change any code that interacts with the payload prior to and up to being put into an event to use the PBJ objects instead of self-serializable. The EventCreator will accept PBJ payloads and wrap each in a self-serializable instance.

### Tasks
- [ ] identify the lifecycle of transactions before they get put into events
- [ ] replace the usage of SS classes with PBJ records
- [ ] same for unit tests

### Notes
- Transactions get put into events in the constructor for `BaseEventHashedData`
- `ConsensusTransactionImpl` will eventually become the payload wrapper that is not SS
- A PBJ record of a payload is `OneOf<PayloadOneOfType>`
