### ISSUE TITLE
HIP-904: TokenClaimAirdrop configurations and integration tests

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#13738]
Following https://github.com/hashgraph/hedera-services/issues/13737 we need to add final configurations for the new `TokenClaimAirdrop` transaction type, as well as provide integration tests coverage.

More details and information about the transaction type can be found in [this design doc](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/docs/design/services/token-service/airdrops/token-claim-airdrop.md).

```[tasklist]
### Tasks
- [x] Add needed changes in `feeSchedule` files, throttle `ThroughputLimits` and `ApiPermissionConfig` for the new operation
- [ ] Implement integration tests for the acceptance tests from the design doc and any additional cases from the test plan
```
```[tasklist]
### Definition of done
- [x] Define the needed changes for the `TokenClaimAirdrop` transaction in `feeSchedules`, throttle definitions and API permissions config
- [ ] Provide integration tests for the acceptance tests from the design doc
```

**Comment by JivkoKelchev** [comment]
All additional tests are tracked by the corresponding epics.
