### ISSUE TITLE
add tests to Dynamic Address Book impl

### ISSUE THREAD

**Issue by povolev15** [hashgraph/hedera-services#13790]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/14174
- [ ] #14177
- [ ] https://github.com/hashgraph/hedera-services/issues/14038
- [ ] https://github.com/hashgraph/hedera-services/issues/14190
```

**Comment by iwsimon** [comment]
All the HapiTests are done here.
