### ISSUE TITLE
Reusable Services

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#13834]
Turn `HandleContext` into a simple container that only references other entities but does not contain business logic. This is required to simplify re-usage because it will be easier to mock or replace the default behavior.

```[tasklist]
### Simplified HandleContext
- [ ] https://github.com/hashgraph/hedera-services/issues/13910
- [ ] https://github.com/hashgraph/hedera-services/issues/13932
- [ ] https://github.com/hashgraph/hedera-services/issues/13934
- [ ] https://github.com/hashgraph/hedera-services/issues/13941
- [ ] https://github.com/hashgraph/hedera-services/issues/13947
- [ ] Extract child dispatcher
- [ ] https://github.com/hashgraph/hedera-services/issues/13972
- [ ] Extract staking award accumulator
```

Implement and modularize reusable facility. 

```[tasklist]
### Extract modules
- [ ] Create functionality that provides SavepointStack on top of the States API
- [ ] Extract module for SavepointStack functionality
- [ ] https://github.com/hashgraph/hedera-services/issues/14166
- [ ] Extract modules for storeRegistry and serviceApiRegistry
- [ ] Create hedera-app-child-dispatcher-facility module _TBD_
- [ ] Create hedera-app-fee-calculation-facility module _TBD_
```

**Comment by netopyr** [comment]
![Image](https://github.com/hashgraph/hedera-services/assets/3652866/6fbde5f4-3d72-4412-ba66-13d2c55e4827)

**Comment by netopyr** [comment]
Depends on #13638

**Comment by netopyr** [comment]
Closing as we decided to follow a different approach
