### ISSUE TITLE
HIP-632 resolve outstanding issues before design/implementation

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#13895]
There are open issues w.r.t. HIP-632 that need resolution.

* [x] Relationship to HIP-631 "virtual addresses"
    * HIP-631 on virtual addresses is not going to be implemented any time soon.  HIP-632 explicitly mentions -631 as something to build on.  Three of the methods in -632 have "virtual address" in their name - instead of, say, "alias".  One of them returns an _array_ of virtual addresses instead of only the zero-or-one alias.  These methods should be fixed to be appropriate for the single alias; and all the text fixed up too.
    * One possibility: simply move the three "virtual address methods" to HIP-631 from HIP-632 (and then erase all mention of virtual addresses from HIP-632, making it independent of HIP-631.
        * But this would leave HAS user unable to go from alias<->Hedera account.  So perhaps instead they should be _replaced_ in HIP-632 by 2 methods to do exactly that, go from alias<->Hedera account.
        * Or both.
    * Possibly HIP-631 should be withdrawn.  It will probably look different anyway, when implemented, due to other changes in the system since.  (E.g., HIP-583.)
    * **Status:** HIP-632 edit to remove virtual addresses in favor of aliases in review - [PR](https://github.com/hashgraph/hedera-improvement-proposal/pull/1011)
* [x] _Correctly_ exposing ability to verify ED signatures to smart contract service. See #14248 
    * There needs to be a proper way for smart contracts service to get access to the app's ability to verify an arbitrary ED or EC signature, given an account, the data, and the signature.  Currently no service has the ability to do that - the only thing exposed is the list of verified signatures (that signed the transaction).  But `isAuthorized{Raw}` requires it.  (`IsAuthorized` requires it for accounts with keys of arbitrary complexity, `isAuthorizedRaw` only for accounts with a single "simple" key.)
    * Currently `isAuthorizedRaw` does it by directly using a platform `Cryptography` crypto engine, but:
        * that API is deprecated-for-removal, and
        * for `isAuthorized` there's the need to grok complex keys
    * A fee calculator (or something) needs to go along with it because the signature verification - to be encapsulated in the app service - has a wide range of cost (keys can be very complex) that the system contract will need to charge.
    * Before a new fee schedule is available we should get a much closer estimate of gas costs for signature verification.
    * **Status:** Interface agreed with services, will proceed in #14248
* [x] (Possibly) handle long-zero addresses in `isAuthorized{Raw}` - currently disallowed by the HIP, but no reason for it not to work - we could update the HIP.
    * **Status:** Agreed, and is in the HIP-632 edit PR above.
* [x] Update HIP-632 to include more response codes (see `IsAuthorizedRawCall.java` comments for a list of needed codes)
    * **Status:** In the HIP-632 edit PR above.

**Comment by david-bakin-sl** [comment]
Decision on "virtual addresses": HIP-632 to be edited to:
* remove mention of virtual address and HIP-631 from -632
   * refer to HIP-583 instead
* make the virtual address methods be appropriate for a single alias
   * `isAlias/getHederaAccountNumAlias/getEvmAddressAlias`
* Leave -631 alone

(FYI: 3 types of alias: "hedera account num alias", "hedera key alias" (ED), "evm address alias" (EC))

(Q: If you have an EC public key you've got both an EVM address and the EC public key - we use the EVM address??)
(Q: What's the "alias" in the Account protobuf (in state)?)

action item: davidbak to look at this, report back

**Comment by david-bakin-sl** [comment]
w.r.t. `isAuthorized` and the protobuf of signatures:  

* how does it look to the SDK user?  Can he create the protobuf of multiple signatures?  If there's only one signature can he get the 64- or 65-byte signature for `isAuthorizedRaw`?

action item: davidbak to talk to SDK team + greg to learn: how would this work most usefully for developers?

**Comment by david-bakin-sl** [comment]
Services team has responded with a proposed interface for providing signature verification.  Looks good - it gives smart contracts both a count of ED+EC keys (for computing fees) and a "visitor" they'll call during the key tree-walk so we can decide on how to verify certain keys (e.g., contract ids).  Still to be finalized (and no schedule yet of course).

**Comment by david-bakin-sl** [comment]
All open issues have decisions - though there is work to be done, tracked as issues.
