### ISSUE TITLE
hedera-cryptography Repository CI/CD

### ISSUE THREAD

**Issue by mxtartaglia-sl** [hashgraph/hedera-services#14100]
```[tasklist]
### Tasks
- [x] Update gradle config to align to hedera-services
- [x] Set up cryptography module (empty)
- [x] In hedera-cryptography repository configure gradle tasking for swirlds-crypto-pairings-signatures module
- [x] In hedera-cryptography repository configure gradle tasking for swirlds-crypto-pairings-api module
- [x] In hedera-cryptography repository configure gradle tasking for swirlds-crypto-altbn128 module
- [x] Configure gradle tasks for swirlds-nativesupport module
- [x] Set up CI/CD pipeline in hedera-crypto to call the basic gradle build checks
- [x] Ensure CI/CD pipeline can publish hedera-crypto artifacts to maven central
- [x] Rust cross-compilation through gradle plugin for mac/windows/linux (:compile-rust)
- [x] Rust compilation tasks occur for local OS - only compile on local computer (:assemble-rust-local)
```

**Comment by rbarkerSL** [comment]
https://github.com/hashgraph/hedera-cryptography/issues/12

**Comment by mxtartaglia-sl** [comment]
UPDATE: Given that I am cross-compiling in Mac when local developing, we should be able to cross-compile in all scenarios and not only in the pipeline.

**Comment by poulok** [comment]
@timo0 is this something you have experience with? Perhaps this would be a good task for you.

**Comment by jjohannes** [comment]
I started looking into running the Rust compilation with Gradle. We can use some code from https://github.com/mozilla/rust-android-gradle/ to invoke Rust. We can't use that plugin as it is as it is bound to the Android Gradle Plugin. That can't be combined with "normal" Java projects. But the plugin already contains functionality to compile Rust for desktop targets. We can use that and cut out the Android specifics. (Apart from that, the plugin has other issues many Gradle plugins have at the moment: uses old/deprecated concepts, incompatibility with the Configuration Cache.)

I would start with the first PR that, based on code from `mozilla/rust-android-gradle`, establishes a Gradle setup that:
   - Has a separate `cargoBuild<Target>` task for the multiple targets
   - Packages the results of the rust compilation into the Jars
   - **Not**: install Rust itself or setup the cross-compilation environment
   - WiP PR: **TODO**

When that is done, we can look at what Gradle can do in terms of getting things setup automatically or if we need/want to enforce certain setups to be done manually first. Basically what @mxtartaglia-sl [has done on his machine](https://github.com/hashgraph/hedera-services/issues/14100#issuecomment-2326846008).

**Comment by jjohannes** [comment]
Implemented by: https://github.com/hashgraph/hedera-cryptography/pull/70, https://github.com/hashgraph/hedera-cryptography/pull/82

**Comment by mxtartaglia-sl** [comment]
- https://github.com/hashgraph/hedera-cryptography/issues/94
- https://github.com/hashgraph/hedera-cryptography/issues/92 
- https://github.com/hashgraph/hedera-cryptography/issues/91
- https://github.com/hashgraph/hedera-cryptography/issues/90 
- https://github.com/hashgraph/hedera-cryptography/issues/89
- https://github.com/hashgraph/hedera-cryptography/issues/20

**Comment by rbarkerSL** [comment]
Is there anything else preventing this ticket from closing?

**Comment by mxtartaglia-sl** [comment]
Hey Roger, It is 100% up to you guys. I created this ticket as Nathan suggested so you and Jendrik could fill it out as needed. The intention was to track what was necessary to complete the CI/CD workflow in the repository. 

The bigger pending I can tell are:
* Mac compilation is disabled in the pipeline.
* Release actions
* Open sourcing
But I know many of those are being tracked somewhere else.
