### ISSUE TITLE
TSS Library: Execute Test Plan and validation for `tss-library`

### ISSUE THREAD

**Issue by mxtartaglia-sl** [hashgraph/hedera-services#14146]
Perform the tests and validations for the parings API and implementation according to what has been defined in #14134

This task is more involved than the tests for the pairings and signatures library because it is testing interactions between multiple signers. Tests must cover a variety of shares, valid and invalid signatures, splitting of shares, etc.

-----

### This task depends on:
- [x] https://github.com/hashgraph/hedera-services/issues/13327
- [x] https://github.com/hashgraph/hedera-services/issues/14134

### Testing notes
- For most tests, we should use participants with the following share breakdown:
  - Participant with ID `1` has 1 share
  - Participant with ID `2` has 2 shares
  - Participant with ID `3` does not exist
  - Participant with ID `4` has 1 share
  - Participant with ID `5` has 3 shares
  - Participant with ID `MAX_INT + 1` has 1 share

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/16463
- [ ] https://github.com/hashgraph/hedera-services/issues/16461
- [ ] https://github.com/hashgraph/hedera-services/issues/16817
- [ ] https://github.com/hashgraph/hedera-services/issues/16818
```

**Comment by poulok** [comment]
OBE
