### ISSUE TITLE
HIP-991: TopicIDs with Fees

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#14170]
Implement permissionless revenue-generating topics described in [HIP-991](https://hips.hedera.com/hip/hip-991) (currently under review).
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/16854
- [ ] https://github.com/hashgraph/hedera-services/issues/16855
- [ ] https://github.com/hashgraph/hedera-services/issues/16856
- [ ] https://github.com/hashgraph/hedera-services/issues/16867
- [ ] https://github.com/hashgraph/hedera-services/issues/15420
- [ ] https://github.com/hashgraph/hedera-services/issues/15516
- [ ] https://github.com/hashgraph/hedera-services/issues/15584
- [x] Review HIP proposal and protobuf specification
- [ ] https://github.com/hashgraph/hedera-services/issues/14365
- [ ] https://github.com/hashgraph/hedera-services/issues/15144
- [ ] https://github.com/hashgraph/hedera-services/issues/15523
- [ ] https://github.com/hashgraph/hedera-services/issues/15524
- [ ] https://github.com/hashgraph/hedera-services/issues/15403
- [ ] https://github.com/hashgraph/hedera-services/issues/15328
- [ ] https://github.com/hashgraph/hedera-services/issues/15513
- [ ] https://github.com/hashgraph/hedera-services/issues/15327
- [ ] https://github.com/hashgraph/hedera-services/issues/15536
- [ ] https://github.com/hashgraph/hedera-services/issues/15537
- [ ] https://github.com/hashgraph/hedera-services/issues/17086
- [ ] https://github.com/hashgraph/hedera-services/issues/17284
- [ ] https://github.com/hashgraph/hedera-services/issues/17348
- [ ] https://github.com/hashgraph/hedera-services/issues/17038
- [ ] https://github.com/hashgraph/hedera-services/issues/17393
- [ ] https://github.com/hashgraph/hedera-services/issues/17506
```
