### ISSUE TITLE
HIP-993: Improve record stream legibility and extensibility

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#14258]
Implement all items listed in [HIP-993](https://hips.hedera.com/hip/hip-993).
```[tasklist]
### Tasks
- [x] Itemized auto-creation fees
- [x] Unified child consensus times
- [x] Fail fast on throttled child transactions
- [x] Clean hollow account completion records
- [x] Synthetic file creations at genesis
- [x] Use natural order for preceding dispatch records
```

**Comment by netopyr** [comment]
Itemized auto-creation fees - done in HandleWorkflow refactor
Unified child consensus times, Use natural order for preceding dispatch records - done in this [PR](https://github.com/hashgraph/hedera-services/pull/14106)
Synthetic file creations at genesis - done in [this PR](https://github.com/hashgraph/hedera-services/pull/14163)

**Comment by netopyr** [comment]
Clean hollow account completion records - done in [this PR](https://github.com/hashgraph/hedera-services/pull/13875)
