### ISSUE TITLE
Clean up SonarCloud stability flags

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1428]
**Summary**
SonarCloud shows a number of bugs and a couple of security issues. 
https://sonarcloud.io/project/issues?id=com.hedera.hashgraph%3Ahedera-services&resolved=false

- [x] Clear all Minor bugs #1433 
- [x] Clear security issues. #1434
- [x] Clear Major Bugs #1435
- [x] Clear Blockers and Critical Bugs #1436

This is the parent issue. All these will be addressed as child issues under this parent issue

**Comment by Neeharika-Sompalli** [comment]
Closing main issue as sub issues are closed
