### ISSUE TITLE
TSS-Ledger-ID: Automatic Bootstrapping For Existing Networks

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#14542]
```[tasklist]
### Design
- [ ] https://github.com/hashgraph/hedera-services/issues/16529
```

```[tasklist]
### Implementation
- [ ] https://github.com/hashgraph/hedera-services/issues/14767
- [ ] https://github.com/hashgraph/hedera-services/issues/16555
- [ ] https://github.com/hashgraph/hedera-services/issues/16556
- [ ] https://github.com/hashgraph/hedera-services/issues/16557
- [ ] https://github.com/hashgraph/hedera-services/issues/16570
- [ ] https://github.com/hashgraph/hedera-services/issues/16644
- [ ] https://github.com/hashgraph/hedera-services/issues/16640
- [ ] https://github.com/hashgraph/hedera-services/issues/16646
```

```[tasklist]
### Delivery
- [ ] https://github.com/hashgraph/hedera-services/issues/14769
```

**Comment by kfa-aguda** [comment]
do we need a task item for a some test (JRS?) that takes an existing network, provides it a new Roster and assert the network is successfully bootstrapped?

**Comment by edward-swirldslabs** [comment]
> do we need a task item for a some test (JRS?) that takes an existing network, provides it a new Roster and assert the network is successfully bootstrapped?

this is done by #14540.  This epic is primarily for the node-operator facing workflow and cryptography management.

**Comment by derektriley** [comment]
Closing this Epic. Any automatic bootstrapping will be done in this epic for exact weight TSS #17191
