### ISSUE TITLE
TokenClaimAirdrop Transaction - Acceptance Tests

### ISSUE THREAD

**Issue by povolev15** [hashgraph/hedera-services#14671]
This list is corresponding to the acceptance tests in [design doc](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/docs/design/services/token-service/airdrops/token-claim-airdrop.md
)

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/14739
- [ ] https://github.com/hashgraph/hedera-services/issues/14741
- [ ] https://github.com/hashgraph/hedera-services/issues/14785
- [ ] https://github.com/hashgraph/hedera-services/issues/14742
- [ ] https://github.com/hashgraph/hedera-services/issues/14743
- [ ] https://github.com/hashgraph/hedera-services/issues/14700
- [ ] https://github.com/hashgraph/hedera-services/issues/14701
- [ ] https://github.com/hashgraph/hedera-services/issues/14703
- [ ] https://github.com/hashgraph/hedera-services/issues/14807
- [ ] https://github.com/hashgraph/hedera-services/issues/14808
- [ ] https://github.com/hashgraph/hedera-services/issues/14809
- [ ] https://github.com/hashgraph/hedera-services/issues/14810
```
