### ISSUE TITLE
Convert legacy smart contract tests to EET

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1469]
- [x] com.hedera.services.legacy.CI.SmartContractSelfDestruct (#330)
- [x] com.hedera.services.legacy.CI.SmartContractFailFirst (#329)
- [x] com.hedera.services.legacy.regression.SmartContractPay (#328)
- [x] com.hedera.services.legacy.regression.SmartContractCRUD (#327)

**Comment by ljianghedera** [comment]
All closed by issue #605
