### ISSUE TITLE
TSS-Roster: implementation epic

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hashgraph/hedera-services#14706]
```[tasklist]
### Data Structures
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Replace AB with Roster
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### API for Services
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Testing
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### External Dependencies
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Launch
- [ ] Add a draft title or issue reference here
```
