### ISSUE TITLE
Convert legacy file tests to EET

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1470]
- [x] com.hedera.services.legacy.file.SystemDeleteIT (#326)
- [x] com.hedera.services.legacy.file.FileServiceIT (#325)
- [x] com.hedera.services.legacy.CI.FilePositiveNegativeTest (#324)
- [x] com.hedera.services.legacy.file.LoadTestIT (#323)
- [x] com.hedera.services.legacy.file.LargeFileUploadIT (#322)
- [x] com.hedera.services.legacy.regression.FileBatchsignatureErrorTestCase (#321)

**Comment by ljianghedera** [comment]
Closed by issue #604 and tracked by issue #661

**Comment by qnswirlds** [comment]
@ljianghedera, there are some left-over file scenarios from #604 that are tracked by #661 as well.
