### ISSUE TITLE
Convert legacy crypto tests to EET

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1471]
- [x] com.hedera.services.legacy.CI.NegativeCryptoQueryTest (#320)
- [x] com.hedera.services.legacy.CI.NegativeAccountCreateTest (#319)
- [x] com.hedera.services.legacy.CI.TxRecordTest (#318)
- [x] com.hedera.services.legacy.CI.MultipleCryptoTransfers (#317)

**Comment by ljianghedera** [comment]
All the sub-issues are closed by issue #661 except one scenario is tracked by #661.
