### ISSUE TITLE
Airdrop Cancel additional tests

### ISSUE THREAD

**Issue by vtronkov** [hashgraph/hedera-services#14938]
Test cases are described here: https://limechain.notion.site/Token-Cancel-airdrop-test-plan-c5d0ba0b8f8e4587bb9d949eeee42021

```[tasklist]
### Tasks
- [x] Airdrop Cancel Test Case 1
- [x] Airdrop Cancel Test Case 2
- [x] Airdrop Cancel Test Case 3
- [x] Airdrop Cancel Test Case 4
- [x] Airdrop Cancel Test Case 6
- [x] Airdrop Cancel Test Case 7
- [x] Airdrop Cancel Test Case 8
- [x] Airdrop Cancel Test Case 9
- [x] Airdrop Cancel Test Case 10
- [x] Airdrop Cancel Test Case 12
- [x] Airdrop Cancel Test Case 24
- [x] Airdrop Cancel Test Case 25
- [x] Airdrop Cancel Test Case 26
- [x] Airdrop Cancel Test Case 27
- [x] Airdrop Cancel Test Case 28
- [x] Airdrop Cancel Test Case 29
- [x] Airdrop Cancel Test Case 30
- [x] Airdrop Cancel Test Case 31
- [x] Airdrop Cancel Test Case 32
- [x] Airdrop Cancel Test Case 33
- [x] Airdrop Cancel Test Case 39
- [x] Airdrop Cancel Test Case 40
- [x] Airdrop Cancel Test Case 41
```
