### ISSUE TITLE
File 0.0.151 upload

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#15048]
```[tasklist]
### Tasks
- [ ] Allow upload of file `0.0.151` by account `0.0.54`
- [ ] Write the file to a configurable place on disk after a successful `FileCreate` or `FileUpdate`
- [ ] Write the file to the configurable place during startup
```
