### ISSUE TITLE
Block Streams Phase 2

### ISSUE THREAD

**Issue by derektriley** [hashgraph/hedera-services#15306]
```[tasklist]
### TSS & Inversion of Control
- [ ] https://github.com/hashgraph/hedera-services/issues/15318
- [x] Have brainstorming session going over design
- [x] TSS test plan
- [ ] https://github.com/hashgraph/hedera-services/issues/15379
- [ ] https://github.com/hashgraph/hedera-services/issues/15367
- [ ] https://github.com/hashgraph/hedera-services/issues/15459
```
See https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/docs/proposals/TSS-Ledger-Id/TSS-Ledger-Id.md

```[tasklist]
### Validators
- [ ] https://github.com/hashgraph/hedera-services/issues/15378
- [ ] https://github.com/hashgraph/hedera-services/issues/15384
- [ ] https://github.com/hashgraph/hedera-services/issues/15474
- [ ] https://github.com/hashgraph/hedera-services/issues/15409
- [ ] ...
```

```[tasklist]
### Block Node Communication
- [ ] https://github.com/hashgraph/hedera-services/issues/15526
- [x] Brainstorming meeting to discuss communication between CN and BN
```
See https://github.com/hashgraph/hedera-block-node/issues/120

```[tasklist]
### Misc
- [ ] https://github.com/hashgraph/hedera-services/issues/14428
- [ ] https://github.com/hashgraph/hedera-services/issues/15131
- [ ] https://github.com/hashgraph/hedera-services/issues/16155
```
