### ISSUE TITLE
HIP-991 Hapi Tests

### ISSUE THREAD

**Issue by anastasiya-kovaliova** [hashgraph/hedera-services#15655]
Implement Hapi tests for permissionless revenue-generating topics described in [HIP-991](https://hips.hedera.com/hip/hip-991) according to the Test Plan: https://www.notion.so/limechain/HIP-991-Test-Plan-a6ecb34ddbcf49cdaf6a3332e25709f1?pvs=4

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/15656
- [ ] https://github.com/hashgraph/hedera-services/issues/15657
- [ ] https://github.com/hashgraph/hedera-services/issues/15658
- [ ] https://github.com/hashgraph/hedera-services/issues/15659
- [ ] https://github.com/hashgraph/hedera-services/issues/15660
- [ ] https://github.com/hashgraph/hedera-services/issues/15661
- [ ] https://github.com/hashgraph/hedera-services/issues/15662
- [ ] https://github.com/hashgraph/hedera-services/issues/15663
- [ ] https://github.com/hashgraph/hedera-services/issues/15664
- [ ] https://github.com/hashgraph/hedera-services/issues/15665
- [ ] https://github.com/hashgraph/hedera-services/issues/15666
- [ ] https://github.com/hashgraph/hedera-services/issues/15667
- [ ] https://github.com/hashgraph/hedera-services/issues/15668
- [ ] https://github.com/hashgraph/hedera-services/issues/15669
- [ ] https://github.com/hashgraph/hedera-services/issues/15670
- [ ] https://github.com/hashgraph/hedera-services/issues/15671
- [ ] https://github.com/hashgraph/hedera-services/issues/15672
- [ ] https://github.com/hashgraph/hedera-services/issues/15673
- [ ] https://github.com/hashgraph/hedera-services/issues/15674
- [ ] https://github.com/hashgraph/hedera-services/issues/15675
- [ ] https://github.com/hashgraph/hedera-services/issues/15676
- [ ] https://github.com/hashgraph/hedera-services/issues/15677
- [ ] https://github.com/hashgraph/hedera-services/issues/15678
- [ ] https://github.com/hashgraph/hedera-services/issues/15679
- [ ] https://github.com/hashgraph/hedera-services/issues/15680
- [ ] https://github.com/hashgraph/hedera-services/issues/15681
- [ ] https://github.com/hashgraph/hedera-services/issues/15682
- [ ] https://github.com/hashgraph/hedera-services/issues/15683
- [ ] https://github.com/hashgraph/hedera-services/issues/15684
- [ ] https://github.com/hashgraph/hedera-services/issues/15685
- [ ] https://github.com/hashgraph/hedera-services/issues/15686
- [ ] https://github.com/hashgraph/hedera-services/issues/15687
- [ ] https://github.com/hashgraph/hedera-services/issues/15688
- [ ] https://github.com/hashgraph/hedera-services/issues/15689
- [ ] https://github.com/hashgraph/hedera-services/issues/15690
- [ ] https://github.com/hashgraph/hedera-services/issues/15691
- [ ] https://github.com/hashgraph/hedera-services/issues/15692
- [ ] https://github.com/hashgraph/hedera-services/issues/15693
- [ ] https://github.com/hashgraph/hedera-services/issues/15694
- [ ] https://github.com/hashgraph/hedera-services/issues/15695
- [ ] https://github.com/hashgraph/hedera-services/issues/15696
- [ ] https://github.com/hashgraph/hedera-services/issues/15697
- [ ] https://github.com/hashgraph/hedera-services/issues/15698
- [ ] https://github.com/hashgraph/hedera-services/issues/15699
- [ ] https://github.com/hashgraph/hedera-services/issues/15700
- [ ] https://github.com/hashgraph/hedera-services/issues/15701
- [ ] https://github.com/hashgraph/hedera-services/issues/15702
- [ ] https://github.com/hashgraph/hedera-services/issues/15703
- [ ] https://github.com/hashgraph/hedera-services/issues/15704
- [ ] https://github.com/hashgraph/hedera-services/issues/15705
- [ ] https://github.com/hashgraph/hedera-services/issues/15706
- [ ] https://github.com/hashgraph/hedera-services/issues/15707
- [ ] https://github.com/hashgraph/hedera-services/issues/15708
- [ ] https://github.com/hashgraph/hedera-services/issues/15709
- [ ] https://github.com/hashgraph/hedera-services/issues/15710
- [ ] https://github.com/hashgraph/hedera-services/issues/15711
- [ ] https://github.com/hashgraph/hedera-services/issues/15712
- [ ] https://github.com/hashgraph/hedera-services/issues/15713
- [ ] https://github.com/hashgraph/hedera-services/issues/15714
- [ ] https://github.com/hashgraph/hedera-services/issues/15715
- [ ] https://github.com/hashgraph/hedera-services/issues/15716
- [ ] https://github.com/hashgraph/hedera-services/issues/15717
- [ ] https://github.com/hashgraph/hedera-services/issues/15718
- [ ] https://github.com/hashgraph/hedera-services/issues/15719
- [ ] https://github.com/hashgraph/hedera-services/issues/15720
- [ ] https://github.com/hashgraph/hedera-services/issues/15721
- [ ] https://github.com/hashgraph/hedera-services/issues/15722
- [ ] https://github.com/hashgraph/hedera-services/issues/15723
- [ ] https://github.com/hashgraph/hedera-services/issues/15724
- [ ] https://github.com/hashgraph/hedera-services/issues/15725
- [ ] https://github.com/hashgraph/hedera-services/issues/15726
- [ ] https://github.com/hashgraph/hedera-services/issues/15727
- [ ] https://github.com/hashgraph/hedera-services/issues/15728
- [ ] https://github.com/hashgraph/hedera-services/issues/15729
- [ ] https://github.com/hashgraph/hedera-services/issues/15730
- [ ] https://github.com/hashgraph/hedera-services/issues/15731
- [ ] https://github.com/hashgraph/hedera-services/issues/15732
- [ ] https://github.com/hashgraph/hedera-services/issues/15733
- [ ] https://github.com/hashgraph/hedera-services/issues/15734
- [ ] https://github.com/hashgraph/hedera-services/issues/15735
- [ ] https://github.com/hashgraph/hedera-services/issues/15736
- [ ] https://github.com/hashgraph/hedera-services/issues/15737
- [ ] https://github.com/hashgraph/hedera-services/issues/15738
- [ ] https://github.com/hashgraph/hedera-services/issues/15739
- [ ] https://github.com/hashgraph/hedera-services/issues/15740
- [ ] https://github.com/hashgraph/hedera-services/issues/15741
- [ ] https://github.com/hashgraph/hedera-services/issues/15742
- [ ] https://github.com/hashgraph/hedera-services/issues/15743
- [ ] https://github.com/hashgraph/hedera-services/issues/15744
- [ ] https://github.com/hashgraph/hedera-services/issues/15745
- [ ] https://github.com/hashgraph/hedera-services/issues/15746
- [ ] https://github.com/hashgraph/hedera-services/issues/15747
- [ ] https://github.com/hashgraph/hedera-services/issues/15748
- [ ] https://github.com/hashgraph/hedera-services/issues/15749
- [ ] https://github.com/hashgraph/hedera-services/issues/15750
- [ ] https://github.com/hashgraph/hedera-services/issues/15751
- [ ] https://github.com/hashgraph/hedera-services/issues/15752
- [ ] https://github.com/hashgraph/hedera-services/issues/15753
- [ ] https://github.com/hashgraph/hedera-services/issues/15754
- [ ] https://github.com/hashgraph/hedera-services/issues/15755
- [ ] https://github.com/hashgraph/hedera-services/issues/15756
- [ ] https://github.com/hashgraph/hedera-services/issues/15757
- [ ] https://github.com/hashgraph/hedera-services/issues/15758
- [ ] https://github.com/hashgraph/hedera-services/issues/15759
- [ ] https://github.com/hashgraph/hedera-services/issues/15760
- [ ] https://github.com/hashgraph/hedera-services/issues/15761
- [ ] https://github.com/hashgraph/hedera-services/issues/15801
- [ ] https://github.com/hashgraph/hedera-services/issues/15802
- [ ] https://github.com/hashgraph/hedera-services/issues/15803
- [ ] https://github.com/hashgraph/hedera-services/issues/15804
- [ ] https://github.com/hashgraph/hedera-services/issues/15805
- [ ] https://github.com/hashgraph/hedera-services/issues/15806
- [ ] https://github.com/hashgraph/hedera-services/issues/15807
- [ ] https://github.com/hashgraph/hedera-services/issues/15808
- [ ] https://github.com/hashgraph/hedera-services/issues/15809
- [ ] https://github.com/hashgraph/hedera-services/issues/15810
- [ ] https://github.com/hashgraph/hedera-services/issues/15811
- [ ] https://github.com/hashgraph/hedera-services/issues/15812
- [ ] https://github.com/hashgraph/hedera-services/issues/15813
- [ ] https://github.com/hashgraph/hedera-services/issues/15814
- [ ] https://github.com/hashgraph/hedera-services/issues/15815
- [ ] https://github.com/hashgraph/hedera-services/issues/15816
- [ ] https://github.com/hashgraph/hedera-services/issues/15817
- [ ] https://github.com/hashgraph/hedera-services/issues/15818
- [ ] https://github.com/hashgraph/hedera-services/issues/15819
- [ ] https://github.com/hashgraph/hedera-services/issues/15820
- [ ] https://github.com/hashgraph/hedera-services/issues/15821
- [ ] https://github.com/hashgraph/hedera-services/issues/15822
- [ ] https://github.com/hashgraph/hedera-services/issues/15838
- [ ] https://github.com/hashgraph/hedera-services/issues/15839
- [ ] https://github.com/hashgraph/hedera-services/issues/15840
- [ ] https://github.com/hashgraph/hedera-services/issues/15841
- [ ] https://github.com/hashgraph/hedera-services/issues/15842
- [ ] https://github.com/hashgraph/hedera-services/issues/15843
- [ ] https://github.com/hashgraph/hedera-services/issues/15844
- [ ] https://github.com/hashgraph/hedera-services/issues/15845
- [ ] https://github.com/hashgraph/hedera-services/issues/15846
- [ ] https://github.com/hashgraph/hedera-services/issues/15847
- [ ] https://github.com/hashgraph/hedera-services/issues/15848
- [ ] https://github.com/hashgraph/hedera-services/issues/15849
- [ ] https://github.com/hashgraph/hedera-services/issues/15850
- [ ] https://github.com/hashgraph/hedera-services/issues/15851
- [ ] https://github.com/hashgraph/hedera-services/issues/15852
- [ ] https://github.com/hashgraph/hedera-services/issues/15853
- [ ] https://github.com/hashgraph/hedera-services/issues/15854
- [ ] https://github.com/hashgraph/hedera-services/issues/15855
- [ ] https://github.com/hashgraph/hedera-services/issues/15856
- [ ] https://github.com/hashgraph/hedera-services/issues/15857
- [ ] https://github.com/hashgraph/hedera-services/issues/15858
- [ ] https://github.com/hashgraph/hedera-services/issues/15859
- [ ] https://github.com/hashgraph/hedera-services/issues/15860
- [ ] https://github.com/hashgraph/hedera-services/issues/15861
- [ ] https://github.com/hashgraph/hedera-services/issues/15862
- [ ] https://github.com/hashgraph/hedera-services/issues/15863
- [ ] https://github.com/hashgraph/hedera-services/issues/15864
- [ ] https://github.com/hashgraph/hedera-services/issues/15865
- [ ] https://github.com/hashgraph/hedera-services/issues/15866
- [ ] https://github.com/hashgraph/hedera-services/issues/15867
- [ ] https://github.com/hashgraph/hedera-services/issues/15868
- [ ] https://github.com/hashgraph/hedera-services/issues/15869
- [ ] https://github.com/hashgraph/hedera-services/issues/15870
- [ ] https://github.com/hashgraph/hedera-services/issues/15871
- [ ] https://github.com/hashgraph/hedera-services/issues/15872
- [ ] https://github.com/hashgraph/hedera-services/issues/15873
- [ ] https://github.com/hashgraph/hedera-services/issues/15874
- [ ] https://github.com/hashgraph/hedera-services/issues/15875
- [ ] https://github.com/hashgraph/hedera-services/issues/15876
- [ ] https://github.com/hashgraph/hedera-services/issues/15877
- [ ] https://github.com/hashgraph/hedera-services/issues/15878
- [ ] https://github.com/hashgraph/hedera-services/issues/15879
- [ ] https://github.com/hashgraph/hedera-services/issues/15880
- [ ] https://github.com/hashgraph/hedera-services/issues/15881
- [ ] https://github.com/hashgraph/hedera-services/issues/15882
- [ ] https://github.com/hashgraph/hedera-services/issues/15883
- [ ] https://github.com/hashgraph/hedera-services/issues/15884
- [ ] https://github.com/hashgraph/hedera-services/issues/15885
- [ ] https://github.com/hashgraph/hedera-services/issues/15886
- [ ] https://github.com/hashgraph/hedera-services/issues/15887
- [ ] https://github.com/hashgraph/hedera-services/issues/15888
- [ ] https://github.com/hashgraph/hedera-services/issues/15889
- [ ] https://github.com/hashgraph/hedera-services/issues/15890
- [ ] https://github.com/hashgraph/hedera-services/issues/15891
- [ ] https://github.com/hashgraph/hedera-services/issues/15892
- [ ] https://github.com/hashgraph/hedera-services/issues/15893
- [ ] https://github.com/hashgraph/hedera-services/issues/15894
- [ ] https://github.com/hashgraph/hedera-services/issues/15895
```
```[tasklist]
### Tasks
```
