### ISSUE TITLE
freshdesk ticket 5794 - create new repository for hedera-gradle-conventions

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-services#15897]
Per [ticket 5794](https://swirldslabs.freshdesk.com/a/tickets/5794) we need to add a new repository to manage the hedera gradle conventions plugins that are used throughout our repository tree inside hashgraph and hiero.

**Tasks**:

- [x] Fill out intake form
- [ ] Fill out open source checklist
- [x] Create Repository
- [ ] Add Gradle Plugins to new repostory
- [ ] Update hedera-services to use the new repository as a source of gradle plugins

**Comment by rbarkerSL** [comment]
`Update hedera-services to use the new repository as a source of gradle plugins` probably needs to be handled under a separate ticket.
