### ISSUE TITLE
Node Operator Query Hapi Tests

### ISSUE THREAD

**Issue by derektriley** [hashgraph/hedera-services#16318]
Implement HAPI Tests or Unit Tests for all of the test cases from the test plan:
https://limechain.notion.site/Allow-Free-Queries-for-Node-Operators-Test-Plan-10510baa8dcd800eae72ffff6b766c7b

Reference this PR https://github.com/hashgraph/hedera-services/pull/15632 for test-client updates.

As this EPIC is being worked, create an issue which indicates which tests you are working on. Update the reference to your issue here and check them off as they are merged. 

- [x] #16320
- [x] #16390
- [x] Tests to try to Perform Other Transactions on the Free Query port (if possible) - Working on this in #16320 
- [x] Perform Node Operator Query Request not from localhost - Working on this in #16320
- [x] #16428
- [x] EDGE CASES
- [x] THROTTLES TEST CASES
	Throttles cases have been tested in #16320

**Comment by mhess-swl** [comment]
Work for this finished with PR #16435
