### ISSUE TITLE
Support Multiple States in Memory

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#16530]
Add support for multiple non-related states in memory. This features is not required today, but may be required in the future by BNs.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/15315
- [ ] https://github.com/hashgraph/hedera-services/issues/15317
- [ ] https://github.com/hashgraph/hedera-services/issues/15316
- [ ] https://github.com/hashgraph/hedera-services/issues/15308
- [ ] #15639
- [ ] https://github.com/hashgraph/hedera-services/issues/15640
- [ ] https://github.com/hashgraph/hedera-services/issues/15945
- [ ] https://github.com/hashgraph/hedera-services/issues/15946
```
