### ISSUE TITLE
Sub-issue 1722- HAPI permissions and throttling 

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1736]
### Problem

This is a sub issue for #1722 for HAPI permissions and throttling

### Solution

- [x] Add a `PermissionFileUtils` key for the new `TokenFeeScheduleUpdate` function and update all _api-permission.properties_ accordingly.
- [x] Update `ExpectedCustomThrottles` to include the new function, and update all throttles _*.json_ (including test resources).
- [x] Add a metric for the function to `MiscUtils`.
- [x] Extend the `TokenController` to override the gRPC stub for the new op.
