### ISSUE TITLE
EETs for TokenFeeScheduleUpdate operation -- subtask for 1722

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1741]
### Problem

Add end to end tests for the new transaction type TokenFeeScheduleUpdate

### Solution

- [x] Translate commented-out `TokenUpdateSpecs` from `TokenUpdate` to `TokenFeeScheduleUpdate` ops.
- [x] Add `feeScheduleKey` cases to `TokenCreateSpecs`.
- [x] Add `feeScheduleKey` cases to `TokenUpdateSpecs`.

**Comment by tinker-michaelj** [comment]
Closed by https://github.com/hashgraph/hedera-services/pull/1760
