### ISSUE TITLE
Staking: Treasury Behavior

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#193]
In order to perform the payment transaction, the treasury must follow these steps

- [ ] Make a copy of the FCM

- [ ] Calculate all Stakes #367 

- [ ] Calculate all Payments #368 

- [ ] Distribute payment to nodes and proxy stakers

- [ ] Update the stake field in the address book for each node to the amount of tinybars staked to the node #371

- [ ] Add to each FCM account the proxy amount and node at the time of the last payment calculation

**Comment by tinker-michaelj** [comment]
Superseded by HIP-406.
