### ISSUE TITLE
Support aliases in all transactions and queries

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#2691]
Currently `alias` is used only in `CryptoTransfer` and `getAccountBalance`/`getAccountInfo`. Extend the support to use `alias` in all other transactions and queries

- [ ] https://github.com/hashgraph/hedera-protobufs/issues/134, [PR](https://github.com/hashgraph/hedera-protobufs/pull/135)

- [ ] #3105 
- [x] #3106
- [x] #3107
- [x] #3109 
- [x] #3110
- [x] #3111
- [x] #3112
- [x] #3113 
- [ ] **EETs and Unit Tests** , [Test Plan ](https://www.notion.so/hedera/Auto-Account-Creation-Test-Plan-24235d2e4b6a439fa625b2746a59b43d)

SDKs
- [x] https://github.com/hashgraph/hedera-sdk-java/issues/848
- [x] https://github.com/hashgraph/hedera-sdk-js/issues/858
- [x] https://github.com/hashgraph/hedera-sdk-go/issues/373

**Comment by SimiHunjan** [comment]
moved to 0.25 release
