### ISSUE TITLE
Support ERC-20/721 allowance and transferFrom methods in token redirect proxy

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#3088]
### Problem

The ERC-20 and ERC-721 "proxy" contracts for HTS tokens introduced by HIP-218 did not support the `approve` and `transferFrom` methods in the standard ERC interfaces.

### Solution

Implement [HIP-376](https://hips.hedera.com/hip/hip-376).

### Sub Issues

- [x] https://github.com/hashgraph/hedera-services/issues/3128
- [x] https://github.com/hashgraph/hedera-services/issues/3127
- [x] https://github.com/hashgraph/hedera-services/issues/3126
- [x] https://github.com/hashgraph/hedera-services/issues/3129
- [x] https://github.com/hashgraph/hedera-services/issues/3125
- [x] https://github.com/hashgraph/hedera-services/issues/3124
- [x] https://github.com/hashgraph/hedera-services/issues/3123
- [x] https://github.com/hashgraph/hedera-services/issues/3122
- [x] https://github.com/hashgraph/hedera-services/issues/3121
