### ISSUE TITLE
Virtualize NFT storage

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#3089]
### Problem

It is quite possible that demand for minted NFTs will exceed the current cap of 50M.

### Solution

Migrate NFT storage to a `VirtualMap`.

**Comment by rjuang** [comment]
Breakdown of work:
- [x] Implement classes (key, value, and factories) needed for VirtualMap
- [x] Draft integration patch to integrate classes to migrate from MerkleMap to Virtual Map  
- [ ] Measure impact of performance of integration patch and resolve issues that come up.
- [ ] Profile performance bottle necks for NFT storage and iterate on improving implementaiton
