### ISSUE TITLE
Improve testing for serialization/deserialization by adding a 

### ISSUE THREAD

**Issue by rjuang** [hashgraph/hedera-services#3114]
### Problem

When code changes happen to the serializable part of serializable data classes, there is no enforcement of testing whether de-serialization of older byte data works properly. 

### Solution

See idea document here:

https://www.notion.so/hedera/Suggestions-for-Uniform-Serialized-Data-testing-fe40606e4d05405d9ee1ab4503be5fed

Basically create a base test class, e.g. `SerializableDataTest<T extends SelfSerializable>`  and have the respective test classes extend from this base test class and implement the abstract methods.

Also, another needed place for this is loading older signed states from different tagged versions.  This can be considered an e2e test to guard against anything that happens incorrectly due to integration across classes.

### Work Breakdown
- [x] Implement `SerializableDataTest` abstract class.  (Michael might start doing this as part of #3072 )
- [x] Refactor tests for self serializable classes to make use of this.
- [x] Add an e2e test to load signed state from a specific version
- [x] Collect various signed state versions (across 3-4 versions)
- [ ] Add descriptive test failure messages to let users know how to fix failing serde tests. This can be due to:
    - [ ] Breaking actual serialization/deserialization path. (current/old version mismatch)
         - [ ] Fix broken assumption
         - [ ] Deprecate old version.
    - [ ] Updating an unstable/unreleased version (current version mismatch)
    - [ ] Adding a new version and updating current version (no file found).
- [ ] Add documentation explaining how to create a new serde test.
- [ ] Can we add a lint check that ensures a serde test exists for all SelfSerializable objects ?

### `SelfSerializable` types needing unit test cleanup
 - [x] `CurrencyAdjustments`
 - [x] `EntityId`
 - [x] `EvmFnResult`
 - [x] `EvmLog`
 - [x] `ExchangeRates`
 - [x] `ExpirableTxnRecord`
 - [x] `FcAssessedCustomFee`
 - [x] `FcCustomFee`
 - [x] `FcTokenAllowance`
 - [x] `FcTokenAllowanceId`
 - [x] `FcTokenAssociation`
 - [x] `FilePart`
 - [x] `MerkleAccountState`
 - [x] `MerkleEntityId`
 - [x] `MerkleNetworkContext`
 - [x] `MerkleSchedule`
 - [x] `MerkleSpecialFiles`
 - [x] `MerkleToken`
 - [x] `MerkleTokenRelStatus`
 - [x] `MerkleTopic`
 - [x] `MerkleUniqueToken`
 - [x] `NftAdjustments`
 - [x] `RecordsRunningHashLeaf`
 - [x] `TxnId`
 - [x] `TxnReceipt`
 - [x] `MerkleAccountTokens`
 - [x] `ContractKey`
 - [x] `ContractValue`
 - [x] `VirtualBlobKey`
 - [x] `VirtualBlobValue`
 - [ ] `RecordStreamObject`

**Comment by rjuang** [comment]
We should consider:
1. Adding a documentation explaining how to add serde tests.
  - This would include process of creating a serde test that is named ObjectNameSerdeTest that extends `SelfSerializableDataTest< ... >`
  - Adding an entry to SerializedForms to ensure an entry can be generated.
2. Linter to check that any new selfserializable classes added have an associated serde test.

**Comment by rjuang** [comment]
Will mark this as resolved since this seems to be understandable how to resolve when serve tests fail.
