### ISSUE TITLE
Standardize entity lookup and validation logic inside `StateView`

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#3206]
### Problem

Every transaction needs to check the usability of some entities: accounts, contracts, files, scheduled transactions, tokens, or topics---e.g. if a topic is deleted, it cannot be used in a `submitMessage`.

Note that for non-contract transactions, all entities can be validated _before handling the transaction_. (For contract transactions, some entities may need to be validated while handling the transaction.)

There are two performance benefits to validating all entities _before_ handling the transaction:
1. The downstream components handling the transaction do not need to repeat the validations.
2. Even better, the validations can be done using a signed state in pre-consensus `handleTransaction`; and **IF** no entity changed or expired between the (consensus) time the state was signed and the time of consensus `handleTransaction`, then the validations don't even need to be repeated at consensus.

The second benefit is exactly what we gain by expanding signatures from the latest signed state. (And with round-based transaction handling, we can even use a thread pool to do these validations concurrently for the entire round! 📍)

But for historical reasons, our usability checks are not now isolated in a single component that can be backed by a signed state (i.e., a `StateView` whose `StateChildren` come from a signed state). And some checks are explicitly done by the same components that update the mutable state while handling the transaction---e.g., `TransferLogic` [validates](https://github.com/hashgraph/hedera-services/blob/affba21f131e86c4817635b7273eeca0da1afacf/hedera-node/src/main/java/com/hedera/services/ledger/TransferLogic.java#L122) that each account with a changing balance is present, non-deleted, and non-expired. 

### Solution

- [ ] Update `StateView` with entity-validation methods that mirror the [`SigMetadataLookup` interface](https://github.com/hashgraph/hedera-services/blob/affba21f131e86c4817635b7273eeca0da1afacf/hedera-node/src/main/java/com/hedera/services/sigs/metadata/SigMetadataLookup.java),
```
ResponseCodeEnum validateAccount(@NotNull AccountID id, @Nullable ValidatedRefs validatedRefs);
ResponseCodeEnum validateContract(@NotNull ContractID id, @Nullable ValidatedRefs validatedRefs);
ResponseCodeEnum validateFile(@NotNull FileID id, @Nullable ValidatedRefs validatedRefs);
ResponseCodeEnum validateSchedule(@NotNull ScheduleID id, @Nullable ValidatedRefs validatedRefs);
ResponseCodeEnum validateToken(@NotNull TokenID id, @Nullable ValidatedRefs validatedRefs);
ResponseCodeEnum validateTopic(@NotNull TopicID id, @Nullable ValidatedRefs validatedRefs);
```
...where `ValidatedRefs` extends `LinkedRefs` to include:
1. A `long earliestLinkedExpiry` field.
2. A `ResponseCodeEnum terminalStatus` field.

...and if the `ValidatedRefs` instance given to a `validated*(id, validatedRefs)` method is non-`null`, update its linked numbers, aliases, earliest expiry, and status.

- [ ] Then add three `default` methods to the `TxnAccessor` interface,
```
default boolean validatesRefsUpFront() {
    return false;
}
default void setStateView(StateView stateView) {
    throw new UnsupportedOperationException();
}
default ValidatedRefs getValidatedRefs() {
    throw new UnsupportedOperationException();
}
```
- [ ] And in `TransitionRunner`, precede the current [one-step validation](https://github.com/hashgraph/hedera-services/blob/affba21f131e86c4817635b7273eeca0da1afacf/hedera-node/src/main/java/com/hedera/services/txns/TransitionRunner.java#L118) with an opportunity to do up-front entity validation:
```
    if (accessor.validatesRefsUpfront()) {
        var validatedRefs = accessor.getValidatedRefs();
        if (validatedRefs.areChangedAccordingTo(changeHistorian)) {
            accessor.setStateView(workingStateView);
            validatedRefs = accessor.getValidatedRefs();
        }
        if (validatedRefs.terminalStatus() != OK) {
            txnCtx.setStatus(validatedRefs.terminalStatus());
            return false;
        }
    }
``` 
- [ ] ...where the `changeHistorian` is a slight generalization of the existing `sigImpactHistorian`.

We can then refactor every transaction type to do as much of its entity validation up-front as it can; and remove duplicate validation work downstream in `handleTransaction`. (Note this goes hand-in-hand with the [refactor to specialized `TxnAccessor` implementations](https://github.com/hashgraph/hedera-services/issues/2691) being done to support aliases.) 
 - [ ] `ConsensusCreateTopic`
 - [ ] `ConsensusDeleteTopic`
 - [ ] `ConsensusSubmitMessage`
 - [ ] `ConsensusUpdateTopic`
 - [ ] `ContractCall`
 - [ ] `ContractCreate`
 - [ ] `ContractDelete`
 - [ ] `ContractUpdate`
 - [ ] `CryptoApproveAllowance`
 - [ ] `CryptoCreate`
 - [ ] `CryptoDeleteAllowance`
 - [ ] `CryptoDelete`
 - [ ] `CryptoTransfer`
 - [ ] `CryptoUpdate`
 - [ ] `FileAppend`
 - [ ] `FileCreate`
 - [ ] `FileDelete`
 - [ ] `FileUpdate`
 - [ ] `ScheduleCreate`
 - [ ] `ScheduleDelete`
 - [ ] `ScheduleSign`
 - [ ] `SystemDelete`
 - [ ] `SystemUndelete`
 - [ ] `TokenAccountWipe`
 - [ ] `TokenAssociateToAccount`
 - [ ] `TokenBurn`
 - [ ] `TokenCreate`
 - [ ] `TokenDelete`
 - [ ] `TokenDissociateFromAccount`
 - [ ] `TokenFeeScheduleUpdate`
 - [ ] `TokenFreezeAccount`
 - [ ] `TokenGrantKycToAccount`
 - [ ] `TokenMint`
 - [ ] `TokenPause`
 - [ ] `TokenRevokeKycFromAccount`
 - [ ] `TokenUnfreezeAccount`
 - [ ] `TokenUnpause`
 - [ ] `TokenUpdate`

**Comment by tinker-michaelj** [comment]
n/a
