### ISSUE TITLE
Capture missing HTS precompile functions design

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-services#3554]
### Problem

HTS Precompile is currently missing some functions.
In v0.28.0 we want to capture the functions and workload necessary

### Solution

Capture design tickets for each method and any foundational work to be done
- [x] updateTokenInfo(symbol, name, treasury, expiry, memo)
- [x] updateTokenExpiryInfo(autoRenewAccount, autoRenewPeriod)
- [x] updateTokenKeys(keyType, key)
- [x] tokenDelete(token)
- [x] tokenPause(token)
- [x] tokenUnpause(token)
- [x] tokenRevokeKyc(token, account)
- [x] tokenGrantKyc(token, account)
- [x] tokenWipeAccount(token, account, amount)
- [x] tokenWipeAccount(token, account, serialNumbers)
- [x] tokenFreeze(token, account)
- [x] tokenUnfreeze(token, account)
- [x] tokenGetInfo(token) 
- [x] tokenGetAutoRenew(token)
- [x] tokenGetDefaultStatus(token)
- [x] isFrozen(token) 
- [x] isKyc(token) 
- [x] tokenGetKey(token, keyType) 
- [x] tokenGetCustomFees(token) 
- [x] tokenGetNftInfo(token, serialNumber)
- [x] ...shared functions or logic

Also note how this work might be impacted by the EVM modularization

**Comment by Nana-EC** [comment]
All features implemented
