### ISSUE TITLE
Epic: Modularize concerns of signing requirements and signature verification

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4034]
### Problem

We want to replace the `SigRequirements` class with service-specific `PreTransactionHandler`'s that use Merkle-agnostic `State` and stores to return the list of cryptographic `TransactionSignature`'s that must sign each type of transaction for it to be handled.

The `TransactionMetadata` should support change-detection (whether entities or aliases) so that we only repeat this work in `handleTransaction` if it is necessary.

Although we will keep `SignedTxnAccessor` _mostly_ intact, its `RationalizedSigMeta` field should no longer exist, being replaced by a `TransactionMetadata` instance.

### Solution

- [x] #4024
- [x] #4025
- [x] #4026

**Crypto:** 

- [x] https://github.com/hashgraph/hedera-services/issues/4050
- [x] https://github.com/hashgraph/hedera-services/issues/4027
- [x] https://github.com/hashgraph/hedera-services/issues/4225
- [x] https://github.com/hashgraph/hedera-services/issues/4226
- [x] https://github.com/hashgraph/hedera-services/issues/4227
- [x] https://github.com/hashgraph/hedera-services/issues/4228
- [x] https://github.com/hashgraph/hedera-services/issues/4229

**Files:** 

- [x] #4028

**Tokens:** 

- [x] #4029

**Topics:** 

- [x] #4030 

**Schedules:** 

- [x] #4031

**Contracts:** 

- [x] #4032

**Util:** 

- [x] #4033

**** 

- [x] #4035

**Comment by nickpoorman** [comment]
Work still needs to be done in the workflows. Need the FileService and Admin Service prehandles.

**Comment by nickpoorman** [comment]
https://github.com/hashgraph/hedera-services/pull/6291

**Comment by nickpoorman** [comment]
Will capture the remaining items in tickets. Moving this as an Epic.

**Comment by mhess-swl** [comment]
Closing as completed
