### ISSUE TITLE
Epic: Implement the `hedera-file-service` modules

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#4215]
- [x] #4456
- [x] https://github.com/hashgraph/hedera-services/issues/4028
- [x] #4455 
- [x] https://github.com/hashgraph/hedera-services/issues/4051
- [x] https://github.com/hashgraph/hedera-services/issues/4255

**Comment by nickpoorman** [comment]
Duplicate of https://github.com/hashgraph/hedera-services/issues/5517
