### ISSUE TITLE
Epic: Build improvements for modularity

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#4222]
- [x] https://github.com/hashgraph/hedera-services/issues/3893
- [x] https://github.com/hashgraph/hedera-services/issues/3895
- [x] https://github.com/hashgraph/hedera-services/issues/3896
- [x] https://github.com/hashgraph/hedera-services/issues/4232
- [x] https://github.com/hashgraph/hedera-services/issues/4233
- [x] https://github.com/hashgraph/hedera-services/issues/4234
- [x] https://github.com/hashgraph/hedera-services/issues/4235
- [x] https://github.com/hashgraph/hedera-services/issues/4236
- [x] https://github.com/hashgraph/hedera-services/issues/4237
- [x] https://github.com/hashgraph/hedera-services/issues/4238
