### ISSUE TITLE
Epic: Support java modules (module-info.java)

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#4239]
We need to refactor the repo to migrate all grade modules the be real java modules

- [x] https://github.com/hashgraph/hedera-services/issues/4238
- [x] https://github.com/hashgraph/hedera-services/issues/4237
- [x] https://github.com/hashgraph/hedera-services/issues/4236
- [x] https://github.com/hashgraph/hedera-services/issues/4235
- [x] https://github.com/hashgraph/hedera-services/issues/4234
- [x] https://github.com/hashgraph/hedera-services/issues/4233
- [x] https://github.com/hashgraph/hedera-services/issues/4232
- [x] https://github.com/hashgraph/hedera-services/issues/4252
- [x] https://github.com/hashgraph/hedera-services/issues/4322
- [x] https://github.com/hashgraph/hedera-services/issues/4324
- [x] https://github.com/hashgraph/hedera-services/issues/4334
- [x] https://github.com/hashgraph/hedera-services/issues/4328
- [x] https://github.com/hashgraph/hedera-services/issues/4341
- [x] https://github.com/hashgraph/hedera-services/issues/4342
- [x] https://github.com/hashgraph/hedera-services/issues/4343
- [ ] https://github.com/hashgraph/hedera-services/issues/4345
- [x] https://github.com/hashgraph/hedera-services/issues/4371
- [x] https://github.com/hashgraph/hedera-services/issues/4254
- [x] https://github.com/hashgraph/hedera-services/issues/4201
- [x] https://github.com/hashgraph/hedera-services/issues/4397
