### ISSUE TITLE
Epic: Restructor structure of the repo

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#4243]
The repo contains several folders and files that might be deprecated and the modules are not all based on the same template. We should refactor the repo to have an easy and understandable structure that makes it much more easy for new developers and open source developers to work on it.

- [x] https://github.com/hashgraph/hedera-services/issues/4242
- [x] https://github.com/hashgraph/hedera-services/issues/4241
- [x] https://github.com/hashgraph/hedera-services/issues/4255
- [x] https://github.com/hashgraph/hedera-services/issues/4254
- [x] https://github.com/hashgraph/hedera-services/issues/4322
- [x] https://github.com/hashgraph/hedera-services/issues/4324
- [x] https://github.com/hashgraph/hedera-services/issues/4336
- [x] https://github.com/hashgraph/hedera-services/issues/4337
- [x] https://github.com/hashgraph/hedera-services/issues/4338
- [x] https://github.com/hashgraph/hedera-services/issues/4339
- [x] https://github.com/hashgraph/hedera-services/issues/4340
