### ISSUE TITLE
Epic: housecleaning

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#4376]
This epic contains all issues that will clean the repo (like removing unused files)

- [ ] https://github.com/hashgraph/hedera-services/issues/4363
- [x] https://github.com/hashgraph/hedera-services/issues/4313
- [x] https://github.com/hashgraph/hedera-services/issues/4243
- [x] https://github.com/hashgraph/hedera-services/issues/4241
- [x] https://github.com/hashgraph/hedera-services/issues/4387
- [x] https://github.com/apache/incubator-tuweni/pull/450
- [x] https://github.com/hashgraph/hedera-services/issues/4429
