### ISSUE TITLE
Epic: Implement HIP 632 (all that's left: some tests in smart contract repo)

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#4619]
### Problem

This is a tracking issue for the implementation of the HIP 632.  

### Solution

Break down HIP 632 into several manageable sub issues/tasks. 

- [x] resolve open issues - #13895
- [x] design docs
    - [x] `isAuthorizedRaw` - #13558 
    - [x] `isAuthorized`
    - [x] alias<->address conversion
- [x] #4620
- [x] #4621
- [x] #4622
- [x] #4623
- [x]  #4624
- [ ] [smart contracts repo #844](https://github.com/hashgraph/hedera-smart-contracts/issues/844)
- [x] method implementations
    - [x] `isAuthorizedRaw` implementation - #14108, #14131\
    - [x] `isAuthorized` implementation - #16092 
    - [x] #15032
- [x] #13560 
- [x] #13895 
- [x] Confirm feature flag on for deployment

**Comment by Nana-EC** [comment]
@lukelee-sl please list the items in the epic description.
This way it's easy to see in one place the progress
e.g. 
- [ ] https://github.com/hashgraph/hedera-services/issues/4620

**Comment by david-bakin-sl** [comment]
At this time, remaining work:

* Examples (tests) in smart contract repo
* `isAuthorized`

**Comment by Nana-EC** [comment]
Moved E2E testing to https://github.com/hashgraph/hedera-smart-contracts/issues/1037.

**Comment by Nana-EC** [comment]
Closing, Product team will take care of the rest
