### ISSUE TITLE
Epic: Fee Facility - Implement fee APIs backed by mono-repo code

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#4733]
Define and API and create an implementation that allows services to charge appropriate fees. This implementation must match the existing behavior of the mono-service exactly.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/7910
- [x] Use fee computation in ingest for proper fee checking
- [x] Use fee computation for paid queries
- [ ] https://github.com/hashgraph/hedera-services/issues/7931
- [x] Update the FeeManager whenever file 0.0.111 is updated
- [x] Update the ExchangeRateManager whenever file 0.0.112 is updated
```

**Comment by nickpoorman** [comment]
Related to: https://github.com/hashgraph/hedera-services/issues/6702
