### ISSUE TITLE
HIP 583 Enhancements + Fuzz Testing

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-services#4801]
### Problem

This epic contains nice to have additional items from HIP 583 related to enhancements and testing.

### Solution

**0.36 A / B**:
- [x] https://github.com/hashgraph/hedera-services/issues/4546
- [x] https://github.com/hashgraph/hedera-services/issues/4673
- [x] https://github.com/hashgraph/hedera-services/pull/4644
- [x] https://github.com/hashgraph/hedera-services/pull/4973
- [x] https://github.com/hashgraph/hedera-services/pull/4921
- [x] https://github.com/hashgraph/hedera-services/issues/4981
- [x] https://github.com/hashgraph/hedera-services/issues/4983
- [x] https://github.com/hashgraph/hedera-services/issues/5009
- [x] https://github.com/hashgraph/hedera-services/issues/5613

Relay:
- [x] https://github.com/hashgraph/hedera-json-rpc-relay/pull/844

**0.37 A / B**:
- [x] https://github.com/hashgraph/hedera-services/issues/4982
- [x] #5020
- [x] https://github.com/hashgraph/hedera-services/issues/4874
- [x] #5023 
- [x] https://github.com/hashgraph/hedera-services/issues/5106
- [x] https://github.com/hashgraph/hedera-services/issues/5873
- [x] https://github.com/hashgraph/hedera-services/issues/5105
- [x] https://github.com/hashgraph/hedera-services/issues/6068

**0.38 A/B**:
- [x] https://github.com/hashgraph/hedera-services/issues/5696
- [x] https://github.com/hashgraph/hedera-services/issues/5708
- [x] https://github.com/hashgraph/hedera-services/issues/4984
- [x] https://github.com/hashgraph/hedera-services/issues/5917
- [x] https://github.com/hashgraph/hedera-services/issues/5961

**0.39 A/B**:
- [x] https://github.com/hashgraph/hedera-services/issues/6051
- [x] https://github.com/hashgraph/hedera-services/issues/5753
- [x] https://github.com/hashgraph/hedera-services/issues/4390
- [x] https://github.com/hashgraph/hedera-services/issues/6203

Fuzz tests: 
- [x] https://github.com/hashgraph/hedera-services/issues/4629
- [x] https://github.com/hashgraph/hedera-services/issues/4630
- [x] https://github.com/hashgraph/hedera-services/issues/4632
- [x] https://github.com/hashgraph/hedera-services/issues/4633

**Comment by Nana-EC** [comment]
@MiroslavGatsanoga and @stoyan-lime closing this as it seems to be completed.
If there's any item that was missed let me know and we can re-open
