### ISSUE TITLE
Improvements: Metrics API

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#5107]
Design and implement an API that allows users to define custom metrics

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/5560
- [ ] Write tickets to capture implementation work
- [ ] https://github.com/hashgraph/hedera-services/issues/9845
```

**Comment by hendrikebbers** [comment]
Current design document: https://github.com/hashgraph/hedera-services/issues/5560

**Comment by poulok** [comment]
closing because we decided not to use an epic to track generic "improvements"
