### ISSUE TITLE
Address Book Initialization

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5486]
Allow the application to perform address book initialization on software upgrades.

```[tasklist]
### Tasks
- [x] #5581
- [x] #5582
- [x] #5642
- [x] #5737
- [x] #5475
- [ ] #5778
- [ ] #5803
- [ ] #5584
- [x] #5738
- [ ] #5476
- [ ] #5477
- [ ] #5487
- [ ] #5930
- [ ] #6077
- [ ] #6065
- [ ] https://github.com/swirlds/swirlds-platform-regression/issues/3322
- [ ] https://github.com/hashgraph/hedera-services/issues/6141
- [ ] #6204
- [ ] https://github.com/hashgraph/hedera-services/issues/6479
```

Dependencies
* 5584
  * 5803
  * 5778
  * 5930
  * 6077
* 6065
  * 5584 - its going to be a mess if 6065 is merged into develop before 5584
