### ISSUE TITLE
Epic: Modularize hedera-smart-contract-service for handle dependencies

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#5520]
**Facilities**
 - [x] Extract `KeyManagement` facility to deal with enforcing immutability checks, validating key updates, etc. as many actions will apply to other entities.
 - [x] Extract `AutoRenewManagement` facility to ensure we don't duplicate e.g. logic for extending an auto-renew account lifetime to at least match its funded entity's lifetime.

**Besu abstraction parity**
 - [x] Make `EvmTxProcessor` input a `WorldUpdater` instead of `WorldState` to allow closer analogy to Besu `TransactionProcessor` and (possibly) reduce the need for a mirror node-specific base class that must avoid calling `commit()`?
 - [x] Wrap Hedera transaction in an `EvmTransaction` with convenience methods for accessing and manipulating gas limits, costs, and fees.
 - [x] Extract `EvmFeesAssessor` for charging up-front cost (data gas + value), code deposit fee, and dealing with refunds; especially to encapsulate sender vs relayer logic matrix.
 - [ ] Use DI for `OperationTracer` instead of constructing internally.
 - [ ] See if `CodeCache` can be eliminated by instead warming the blobs `VirtualMap` in pre-handle.
 - [x] "Pull down" alias resolution logic into any component where `EvmTxProcessor` is forced to explicitly convert to a long-zero address before use.

**Besu impedance mismatches**
 - [x] _(SPIKE)_ Evaluate rewriting the Besu `WorldUpdater` hierarchy with an internal account representation that integrates both system contract and EVM balance changes, with first-class support for mutations of Hedera native entities and aliases.
 - [x] _(SPIKE)_ Evaluate journaling for this Hedera-native updater type hierarchy.

**Fees**
 - [ ] Ensure the `node`/`network`/`service` fee decomposition makes sense for the case that `sender` balance < `upfrontCost`.

**Signatures**
 - [x] Ensure the `TransactionDispatcher` supports a way to do "approval fallbacks" when a dispatched `CryptoTransfer` includes a debit whose relevant key isn't active.
 - [x] Ensure the `TransactionDispatcher` will support grandfather'ed signature verification.

**Records**
 - [x] Determine how records created in a message call will automatically follow the `commit()`/`revert()` lifecycle.
 - [ ] Design how value sent in internal message call will be distributed across records.
 - [ ] Identify responsibilities and expectations for records created in the following cases: `selfdestruct`, `CONTRACT_CREATION` message call, internal hollow account creation, `EthereumTransaction` hollow account creation, auto-account creation, following system contract child (`SUCCESS`, failure/`null` response, `REVERT`), itemized storage rent fees.
 - [ ] Determine how and where the limits on "preceding" and "following" child records will be enforced.
 - [x] Ensure record creation continues to guarantee zero-sum hbar transfer lists across all parent and children in a transaction.

**Handlers**
- [x] ContractCallHandler
- [x] ContractCreateHandler
- [x] ContractDeleteHandler
- [x] ContractSystemDeleteHandler
- [x] ContractSystemUndeleteHandler
- [x] ContractUpdateHandler
- [ ] EtherumTransactionHandler

**Comment by nickpoorman** [comment]
Blocked by sub-tasks.

**Comment by nickpoorman** [comment]
Depends on Replay https://github.com/hashgraph/hedera-services/issues/6115

**Comment by nickpoorman** [comment]
https://github.com/hashgraph/hedera-services/issues/6901

**Comment by Neeharika-Sompalli** [comment]
This ticket mainly has dependencies from handle workflow. Other ticket for smart contract service implementations is https://github.com/hashgraph/hedera-services/issues/6901

**Comment by Nana-EC** [comment]
@tinker-michaelj, @netopyr and @lukelee-sl can we consider the items here completed or is there anything remaining?
moving ticket to 0.46

**Comment by netopyr** [comment]
Closing this ticket as the remaining sub tasks are tracked elsewhere
