### ISSUE TITLE
Switch to PBJ

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5557]
Migrate platform data to use PBJ DataIO and Protobuf serialization.

Suggested Set:

Migrate platform data to use PBJ DataIO and Protobuf serialization.
All work in this item must be behind a feature flag (WOWO) to assist stable deployment.

TODO - ensure branch from @rbair23 is merged before starting work on these tasks

```[tasklist]
### Tasks
- [ ] #5599
- [ ] #5600
- [ ] #5604
- [ ] #8344
- [x] #5558
- [ ] #5589
- [ ] #5590
- [ ] #5588
- [ ] #5591
- [ ] #5592
- [ ] #5593
- [ ] #5594
- [ ] #5596
- [ ] #5598
- [x] #5601
- [x] #5602
- [ ] #5603
- [ ] #5605
- [x] #7503
- [x] #7544 
- [x] #7669
- [x] #9722
- [ ] #9942   
```

**Comment by jsync-swirlds** [comment]
Suggested edit:

Migrate platform data to use PBJ DataIO and Protobuf serialization.
All work in this item must be behind a feature flag (WOWO) to assist stable deployment.

### Issues
- [ ] #5558

### Tasks (Issues to be created)
- [ ] Identify ByteBuffer and serialization events
- [ ] Identify serialization requirements (which objects, how often used, etc...)
- [ ] Update PBJ DataIO to support all platform-data serialization requirements
- [ ] Test and verify updated PBJ DataIO
- [ ] Modify platform data to use PBJ DataIO serialization
- [ ] Repeat the following for each object type
  * Select an object type
  * Modify serialization for that object to use PBJ
  * Extend DataIO if needed for this object
  * Ensure proper data migration for that object from existing to PBJ
  * Test and verify correct operation and no performance regression
- [ ] Modify platform data to use the PBJ DataIO for buffered input/output
  - [ ] This includes migration from ByteBuffer and java.io to PBJ DataInput and/or DataOutput implementations
    - [ ] Identify use of stream IO and replace with DataIO
      - [ ] Extend DataIO as necessary
    - [ ] Move any use of Misc.unsafe for IO into DataIO
    - [ ] Modify DataIO, if necessary, to match/incorporate mmap work Artem has done
- [ ] Run thorough performance testing with the PBJ DataIO enabled
  - [ ] Verify no performance regression
- [ ] Identify data migration requirements
  - [ ] Including network restart performance impact, possible interaction impacts, and potential failure modes.
- [ ] Implement a data migration process to be used when the migration feature flag is enabled
- [ ] Run thorough functional and performance testing of the data migration
  - [ ] Verify no functional regression
  - [ ] Verify migration performance is sufficient to enable a timely network upgrade
  - [ ] Document expected time impact during network upgrade for node operators
- [ ] Work with release engineering and devops on release plans and appropriate network upgrades
