### ISSUE TITLE
Parse transactions from pre-OA event stream

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#5659]
Create a tool that can read old event stream files and output the transactions in a readable format.

**Time frame:** 12/16/2018 to 06/12/2019 (16 dec 2018 - 12 jun 2019, helpful for non-Americans)

Tasks:
- [ ] Document SDK versions on mainnet within timeframe
- [ ] Download samples of event stream files
- [ ] Create event stream parser for files from timeframe
- [ ] Create transaction parser for transactions in timeframe
