### ISSUE TITLE
Preconsensus Event Stream

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5682]
In order to support the consensus improvements required for dynamic address book, pre-consensus events must be written to an event stream and replayed on node start up.

```[tasklist]
### Infrastructure
- [ ] #5338
- [ ] #5631
- [ ] #5761
- [ ] #5777
- [ ] https://github.com/hashgraph/hedera-services/issues/6676
- [ ] https://github.com/hashgraph/hedera-services/issues/6677
- [ ] https://github.com/hashgraph/hedera-services/issues/6688
- [ ] https://github.com/hashgraph/hedera-services/issues/6833
- [ ] https://github.com/hashgraph/hedera-services/issues/6874
- [ ] https://github.com/hashgraph/hedera-services/issues/6875
- [ ] https://github.com/hashgraph/hedera-services/issues/6881
- [ ] https://github.com/hashgraph/hedera-services/issues/6924
- [ ] https://github.com/hashgraph/hedera-services/issues/7008
```

```[tasklist]
### Cleanup
- [ ] #5853
- [ ] #5786
- [ ] https://github.com/hashgraph/hedera-services/issues/5931
- [ ] https://github.com/hashgraph/hedera-services/issues/6084
- [ ] https://github.com/hashgraph/hedera-services/issues/6083
- [ ] https://github.com/hashgraph/hedera-services/issues/6082
- [ ] https://github.com/hashgraph/hedera-services/issues/6416
- [ ] https://github.com/hashgraph/hedera-services/issues/6433
- [ ] https://github.com/hashgraph/hedera-services/issues/6435
- [ ] https://github.com/hashgraph/hedera-services/issues/6437
- [ ] https://github.com/hashgraph/hedera-services/issues/6439
- [ ] https://github.com/hashgraph/hedera-services/issues/6438
- [ ] https://github.com/hashgraph/hedera-services/issues/6548
- [ ] https://github.com/hashgraph/hedera-services/issues/6565
```

```[tasklist]
### Integration
- [ ] #5396
- [ ] #5678
- [ ] #5586
- [ ] #5397
```

```[tasklist]
### Adjacent
- [ ] #6026
- [ ] https://github.com/hashgraph/hedera-services/issues/6093
```

```[tasklist]
### Testing
- [ ] #5783
- [ ] https://github.com/hashgraph/hedera-services/issues/6868
- [ ] https://github.com/hashgraph/hedera-services/issues/6876
- [ ] https://github.com/hashgraph/hedera-services/issues/6877
- [ ] https://github.com/hashgraph/hedera-services/issues/6878
- [ ] https://github.com/hashgraph/hedera-services/issues/6882
- [ ] https://github.com/hashgraph/hedera-services/issues/6883
```
