### ISSUE TITLE
Data on Disk

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#5739]
To improve scalability, we need to switch from in-memory data structure to on-disk data structures for accounts, tokens, NFTs, and other entities. Anything currently using MerkleMap should use VirtualMap.

```[tasklist]
### Tasks
- [x] #5636
- [x] #5314
- [x] #5269
- [ ] #5090
- [x] #5446
- [ ] https://github.com/hashgraph/hedera-services/issues/6324
- [ ] https://github.com/hashgraph/hedera-services/issues/6325
- [ ] https://github.com/hashgraph/hedera-services/issues/6326
- [ ] https://github.com/hashgraph/hedera-services/issues/6488
```
