### ISSUE TITLE
Epic: Modularize Token Service Implementation

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#5767]
In phase one, we will see a full CI run pass, with Token Service operations largely performed by workflows and modularized business logic and the Merkle tree root being `MerkleHederaState`.

📨 **The issue is still in draft and will be completed with sub-issues**

### Staking Service And CryptoTransfer Implementation
- [x] https://github.com/hashgraph/hedera-services/issues/5523
- [x] #6395.
- [x] #6412 
- [x] #7217 

### PBJ
 - [x] #5804
 - [x] #6104
 - [x] #7092

### PRE-HANDLE 
Pre-handle will now be "workflow-aware", so within `HederaMerkleState#preHandle`, we will first extract the function, and then either call into the `mono-service`signature expansion; or into the pre-handle workflow.

_Tasks_

- [x] #5862
- [x] #5805
- [x] #5806

### HANDLE 
Once again handle will become workflow-aware, so that within `HederaMerkleState` we can immediately adapt a platform `Transaction` with metadata derived from the pre-handle workflow into a `SignedTxnAccessor`. 

However, instead of delegating the final business logic to a `TransitionLogic`, this must be done via a `Handler` that (as in INGEST),
 - Uses the States API for persistence.
 - Receives facilities/context with API's that approximate the final SPI versions.

_Tasks_
- [x] #5867
- [x] #6113
- [x] #6547
- [x] #7002
- [x] #5770
- [x] #5771

### QUERY
As above, ideally the adapters are implementing API's that approximate what we expect to be the final versions. (Or at least are highly suggestive of what will have changed/improved in the final API's.)

- [x] #5773
- [x] #5772

### Testing
- [ ] #7067
- [ ] Support anything needed to test code for comparing current and new record stream files relating to tokens
- [ ] https://github.com/hashgraph/hedera-services/issues/7676
