### ISSUE TITLE
ThreadManager V1.5

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#5801]
This epic contains all issues that are related to the ThreadManager interface.
In Future we will design a general architecture of thread handling that will be defined in https://github.com/hashgraph/hedera-services/issues/6963

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/5787
- [ ] https://github.com/hashgraph/hedera-services/issues/5788
- [x] https://github.com/hashgraph/hedera-services/issues/5800
```
