### ISSUE TITLE
Improvements: Configuration API

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#5812]
This epic contains a lit of all improvements / bugs / .. regarding the config API.

```[tasklist]
### Tasks
- [x] https://github.com/hashgraph/hedera-services/issues/5380
- [ ] https://github.com/hashgraph/hedera-services/issues/5168
- [ ] https://github.com/hashgraph/hedera-services/issues/5549
- [x] https://github.com/hashgraph/hedera-services/issues/5102
- [ ] https://github.com/hashgraph/hedera-services/issues/5294
- [x] https://github.com/hashgraph/hedera-services/issues/5389
- [ ] https://github.com/hashgraph/hedera-services/issues/5285
- [ ] https://github.com/hashgraph/hedera-services/issues/5289
- [ ] https://github.com/hashgraph/hedera-services/issues/5322
- [ ] https://github.com/hashgraph/hedera-services/issues/5323
- [ ] https://github.com/hashgraph/hedera-services/issues/5325
- [ ] https://github.com/hashgraph/hedera-services/issues/5329
- [ ] https://github.com/hashgraph/hedera-services/issues/5384
- [ ] https://github.com/hashgraph/hedera-services/issues/5388
- [ ] https://github.com/hashgraph/hedera-services/issues/5274
- [ ] https://github.com/hashgraph/hedera-services/issues/5449
- [ ] https://github.com/hashgraph/hedera-services/issues/5646
- [x] https://github.com/hashgraph/hedera-services/issues/5813
- [x] https://github.com/hashgraph/hedera-services/issues/6001
- [ ] https://github.com/hashgraph/hedera-services/issues/6002
- [ ] https://github.com/hashgraph/hedera-services/issues/6032
- [ ] https://github.com/hashgraph/hedera-services/issues/6106
- [ ] https://github.com/hashgraph/hedera-services/issues/6228
- [ ] https://github.com/hashgraph/hedera-services/issues/6229
- [x] https://github.com/hashgraph/hedera-services/issues/6429
- [ ] https://github.com/hashgraph/hedera-services/issues/6935
- [ ] https://github.com/hashgraph/hedera-services/issues/6997
- [ ] https://github.com/hashgraph/hedera-services/issues/7290
- [ ] https://github.com/hashgraph/hedera-services/issues/7351
- [ ] https://github.com/hashgraph/hedera-services/issues/7352
- [ ] https://github.com/hashgraph/hedera-services/issues/7375
- [ ] https://github.com/hashgraph/hedera-services/issues/8069
- [ ] https://github.com/hashgraph/hedera-services/issues/8877
- [ ] https://github.com/hashgraph/hedera-services/issues/7384
```

**Comment by poulok** [comment]
closing because we decided not to use an epic to track generic "improvements"
