### ISSUE TITLE
Platform Base API Cleanup

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#5846]
This epic is about the modularization of all code / modules that belongs to the platform. This includes work with gradle to define better gradle modules and dependencies and work with the Java module system.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/5162
- [ ] https://github.com/hashgraph/hedera-services/issues/5187
- [ ] https://github.com/hashgraph/hedera-services/issues/5293
- [ ] https://github.com/hashgraph/hedera-services/issues/5240
- [ ] https://github.com/hashgraph/hedera-services/issues/5264
- [ ] https://github.com/hashgraph/hedera-services/issues/5271
- [ ] https://github.com/hashgraph/hedera-services/issues/5275
- [ ] https://github.com/hashgraph/hedera-services/issues/5681
- [ ] https://github.com/hashgraph/hedera-services/issues/5815
- [ ] https://github.com/hashgraph/hedera-services/issues/5845
- [ ] https://github.com/hashgraph/hedera-services/issues/5847
- [x] https://github.com/hashgraph/hedera-services/issues/5970
- [x] https://github.com/hashgraph/hedera-services/issues/5975
- [ ] https://github.com/hashgraph/hedera-services/issues/5979
- [ ] https://github.com/hashgraph/hedera-services/issues/6645
- [ ] https://github.com/hashgraph/hedera-services/issues/6648
```

**Comment by hendrikebbers** [comment]
Some issues of https://github.com/hashgraph/hedera-services/issues/7148 belongs to this epic

**Comment by hendrikebbers** [comment]
All issues are listed in epic https://github.com/hashgraph/hedera-services/issues/7148
