### ISSUE TITLE
Degraded Node Detection

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#6072]
There are a million reasons why a node might become degraded, ranging from bugs to internet weather. We should have a mechanism for detecting degraded performance, and we should take action to mitigate its impact on end users.

See #6296 for the proposal of how degraded node performance will be detected and addressed

```[tasklist]
### Tasks
- [x] https://github.com/hashgraph/hedera-services/issues/6081
- [ ] https://github.com/hashgraph/hedera-services/issues/6213
- [ ] https://github.com/hashgraph/hedera-services/issues/6295
- [ ] https://github.com/hashgraph/hedera-services/issues/6296
- [ ] https://github.com/hashgraph/hedera-services/issues/6986
- [ ] https://github.com/hashgraph/hedera-services/issues/6297
- [ ] https://github.com/hashgraph/hedera-services/issues/6968
- [ ] https://github.com/hashgraph/hedera-services/issues/7308
- [ ] https://github.com/hashgraph/hedera-services/issues/7390
```

```[tasklist]
### Related Tickets
- [ ] #5405 
```

**Comment by poulok** [comment]
I'm not sure I agree with removing the `DISCONNECTED` state. I have found it useful when debugging issues, and removing it may cause extra work in JRS tests that rely on platform status log markers.

**Comment by poulok** [comment]
Also, I don't think we should base the decision to go into a degraded state based on the consensus time of self events. A node that is experiencing connectivity issues will likely create very few, or even no events because its intake queue will be large. Perhaps it should be based instead on the size of the transaction pool. If it reaches 90% capacity, we go into a degraded state.

**Comment by poulok** [comment]
It would be good to put the transition to `DEGRADED` behind a dynamic feature flag.

**Comment by alittley** [comment]
@poulok I agree with @cody-littley that `DISCONNECTED` doesn't belong as a state, for a couple reasons

1. A `DISCONNECTED` status greatly complicates the state machine. for example, it shouldn't be possible to transition from `STARTING_UP` to `FREEZE_COMPLETE`. But if any state can move to `DISCONNECTED`, and `DISCONNECTED` can lead to any state, we arrive at this awkward situation:

![image](https://github.com/hashgraph/hedera-services/assets/102969658/06f7fa78-e8d7-4786-8576-bea150a9590e)

So, we'd always have to keep track of what state we *came from* when becoming disconnected... not good.

2. It's just a special case representation of # of connections. I think we should just monitor the corresponding metric to determine if we have 0 connections
