### ISSUE TITLE
Go Replacement : Migrate State and Configuration Management

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/hedera-services#6090]
```[tasklist]
### Tasks
- [ ] Implement `nmt_write_tool_state`  => `common.WriteToolState`
- [ ] Implement `nmt_apply_tool_state` => `common.LoadToolState`
- [ ] Implement `check_tool_integrity` => `common.CheckNodeFolders`
```
