### ISSUE TITLE
Admin service - Handle each of the freeze types

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#6195]
Handle each of the following freeze types in the Freeze Service (admin service).

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/6196
- [ ] https://github.com/hashgraph/hedera-services/issues/6197
- [ ] https://github.com/hashgraph/hedera-services/issues/6198
- [ ] https://github.com/hashgraph/hedera-services/issues/6199
- [ ] https://github.com/hashgraph/hedera-services/issues/6200
- [x] unknownFreezeType
- [ ] https://github.com/hashgraph/hedera-services/issues/6415
```
