### ISSUE TITLE
Freeze Service - prepareUpgrade

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#6196]
Freeze Service prepareUpgrade depends on File Service and Network Service.

prepareUpgrade extracts the upgrade file, writes a marker file and then updates the network service that the upgrade is prepared. 

To do this, the Freeze Service needs to be able to:
- [ ] read the file from the File Service (depends on #6234 which depends on #6178 )
- [x] write out a marker file saying that this upgrade is ready. Implemented in #6225 
- [ ] update a property in Network Service to say the upgrade is ready. Depends on Network Service #6201

**Comment by nickpoorman** [comment]
Depends on https://github.com/hashgraph/hedera-services/issues/6154
