### ISSUE TITLE
Provide handle dependencies for NetworkAdmin Service

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#6415]
### Tasks
- [x] Check for privileged account access ([Issue #6131](https://github.com/hashgraph/hedera-services/issues/6131))
- [x] Access to SwirldDualState
- [x] Cache<TransactionID, Long> execNanosCache for NetworkGetExecutionTimeHandler (We decided  on modularization call that ExecutionTimeQuery is not needed 5/4/2023)
- [x]  All the logic for UncheckedSubmitHandler needs to be implemented in the workflow /app level to be able to submit a unchecked submit

**Comment by netopyr** [comment]
@kimbor Can we close this issue?

**Comment by kimbor** [comment]
> @kimbor Can we close this issue?

Yes
