### ISSUE TITLE
Work out what Handle must provide to support Token Service, deliver to Handle Issue

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#6417]
Also specified in Handle issue is https://github.com/hashgraph/hedera-services/issues/4211 Notion page.

```[tasklist]
### Tasks
- [ ] Need `MerkleNetworkContext` for staking and others. Still not clean if we will store them in each service state
```

```[tasklist]
### Tasks
- [ ]  EntityIdSource - need this to be provided in order to create new entities. Currently we have this as `LongSupplier newEntityNumSupplier();` in `HandleContext`. So, it is not a blocker
```

```[tasklist]
### Tasks
- [ ] EntityCreator - Factory  for creating synthetic records.  
- [ ] SyntheticTxnFactory -  Factory for creating synthetic transactions transactions 
```

```[tasklist]
### Tasks
- [ ] Pending creations (AutoCreationLogic) and in-progress child records. specifically for auto account creation
```

```[tasklist]
### Tasks
- [ ] Fees - a fee calculator, particularly for network fees. Also for Queries
```

```[tasklist]
### Tasks
- [ ] NodeInfo - needed for staking. including network address book
```

```[tasklist]
### Tasks
- [ ] RecordsHistorian - hollow account finalization
```

```[tasklist]
### Tasks
- [ ] FunctionalityThrottling - needed for staking
```

```[tasklist]
### Tasks
- [ ] States API to use for FCQueue. Need for MerklePayerRecords
```

**Comment by mhess-swl** [comment]
Added notes to the Notion page today for required token service dependencies

**Comment by Neeharika-Sompalli** [comment]
All requirements are recorded in the issue and notion page. Closing the issue
