### ISSUE TITLE
Contract Accounts Nonces Externalization

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#6512]
This epic contains items for Contract Accounts Nonces Externalization HIP.

**0.38 B**:
- [x] #6513

**0.39 A/B**:
- [x] https://github.com/hashgraph/hedera-services/issues/6720

**0.40 A/B**:
- [x] https://github.com/hashgraph/hedera-protobufs/pull/257
- [x] https://github.com/hashgraph/hedera-services/issues/6942
- [x] https://github.com/hashgraph/hedera-services/issues/3640
- [x] #6961
- [x] #7124
- [x] #7126
- [x] #7326
- [x] #7424

**Comment by MiroslavGatsanoga** [comment]
Closing this epic as all related items to it are done.
