### ISSUE TITLE
Remove Apache Commons dependency from Platform

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/hedera-services#6648]
### Problem

We should not be importing all of Apache Commons just for a few classes we are using.

### Solution

Add our own Pair and Triple classes to platform for everyone to use. Replace simple usages of:

- ToStringBuilder
- EqualsBuilder
- HashCodeBuilder
- FileUtils
- StopWatch

with our own versions or simple standard Java code. My preference is to use standard java code and core libraries where ever possible. Other places we add our own util classes. They are mostly only used in tests.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/7937
- [ ] https://github.com/hashgraph/hedera-services/issues/7948
- [ ] https://github.com/hashgraph/hedera-services/issues/8008
- [ ] https://github.com/hashgraph/hedera-services/issues/8010
- [ ] https://github.com/hashgraph/hedera-services/issues/8014
- [ ] https://github.com/hashgraph/hedera-services/issues/8041
- [ ] https://github.com/hashgraph/hedera-services/issues/8096
```
