### ISSUE TITLE
Epic: Special Files Facility: Handle updates to special files

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#6856]
This is for the special files facility, which runs immediately after the file service update handler. If the file updated is one of the special data files (e.g. throttles), then extract the bytes and calls the mono service code to update the special file data. Use the existing interceptors if possible (e.g. `ThrottleDefsManager`).

If the mono service determines that the content is invalid, then fail the transaction with the appropriate response code
```[tasklist]
### Tasks
- [ ] Create base "Special Files Handling" in workflow consisting of a method or class called after FileService completes an append or update successfully.
- [ ] https://github.com/hashgraph/hedera-services/issues/7052
- [ ] https://github.com/hashgraph/hedera-services/issues/4729
- [ ] https://github.com/hashgraph/hedera-services/issues/4733
- [ ] Add functionality to the workflow "Special Files Handling" to update Address Book in network context/config/state when file 0.0.101 is updated.
- [ ] Add functionality to the workflow "Special Files Handling" to update Node Details in network context/config/state when file 0.0.102 is updated.
- [ ] Add functionality to the workflow "Special Files Handling" to update HAPI Permissions in network context/config/state when file 0.0.122 is updated.
```
Possibly related: issue #8660

**Comment by kimbor** [comment]
Related: https://github.com/hashgraph/hedera-services/issues/6234
