### ISSUE TITLE
Complete `Scope`-based EVM transaction processing

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#6901]
### Problem

Given the `Account` and `WorldUpdater` implementations in https://github.com/hashgraph/hedera-services/pull/6895, where instead of directly mutating state such as:
 - Account balances, first contract keys, # of K/V pairs; and,
 - In-progress records,
 - Aliases; and,
 - Entity ids

...the `ContractService` dispatches such changes through a `Scope`.

Now, there are three main consumers of `Account`s and `WorldUpdater`s:
   1. EVM operations.
   2. EVM message processors (`CALL` and `CONTRACT_CREATION`)
   3. The top-level EVM transaction processors.

We need to refactor each to use the affordances of the new types.

### Solution

1️⃣ Refactor each `Operation`:
 - [x] #6928
 - [x] #6950
 - [x] `HederaDelegateCallOperation`
 - [x] `HederaDelegateCallOperationV038`
 - [x] #6954
 - [x] #6903
 - [x] #6902
 - [x] #7358
 - [x] `HederaExtCodeCopyOperation`
 - [x] `HederaExtCodeCopyOperationV038`
 - [x] `HederaExtCodeHashOperation`
 - [x] `HederaExtCodeHashOperationV038`
 - [x] `HederaExtCodeSizeOperation`
 - [x] `HederaExtCodeSizeOperationV038`

2️⃣ Refactor the existing `MessageCallProcessor` types and subclass `ContractCreationProcessor` (since it can no longer directly call `Account.setBalance()` and must dispatch its `transferValue()` action):
 - [x] `HederaEvmMessageCallProcessor` -> `HederaMessageCallProcessor`
 - [x] `HederaEvmMessageCallProcessorV038` -> `HederaMessageCallProcessorV038`
 - [x] #7387

3️⃣ Create a (closer) analogy to Besu's `MainnetTransactionProcessor` that:
 - [x] #6905
 - [x] Takes a `WorldUpdater`, a Besu `Transaction` (possibly translated from HAPI `ContractCallTransactionBody` or `ContractCreateTransactionBody`), and any necessary context (e.g. `gasPrice`, `relayer`, etc); and,
 - [x] #7560
 - [x] #7213
 - [x] #7261
 - [x] #7421

4️⃣ Replace `HTSPrecompiledContract` with a dispatch-based precompile that "simply",
 - [x] #7862 
 - [ ] Decodes the given `Bytes` based on selector into a synthetic `TransactionBody`; then,
 - [ ] Computes gas cost based on the `Scope`'s fee calculator; then,
 - [ ] Either dispatches this `TransactionBody` and encodes the response code; or,
 - [ ] Uses readable state from the `Scope` and returns the appropriate information.
