### ISSUE TITLE
Epic - Quality of Life and PR Workflow Stability Improvements

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-services#7009]
### Problem

Currently, the testing process is a major time cost for each PR, and the necessity to run these checks several times per PR compounds that cost.

### Solution

We include here a set of proposed changes that individually improve the situation, and collectively may produce dramatic savings in time and resources.

- [ ] Reduce or remove dependence on Static State for **testing** in the platform and services.
- [ ] Reduce or remove dependence on global properties files for **testing** in the platform and services.
- [x] #6994 
- [ ] Split the unit tests into a few groups (perhaps 8?) and run those in parallel to reduce wall-time required.
- [ ] Remove the need to build the full system for each of the unit/EET/Integration/etc... tests (so only one task runs the full build).
- [ ] Use pre-built OCI images and copy or bind-mount the build output into the test containers, instead of rebuilding the OCI image (taking 8-10 minutes) for each integration test run.
- [ ] Move some of the largest test groups, that test code that's rarely modified, into a separate test run and CI tag ("CI:LongTests"?) only run at the very end of a PR rather than running for every update during a PR.
- [ ] Research if we can add heuristics to determine when a few low-risk test groupings can be elided (i.e. when the tested code is not changed, and none of its dependencies changed).
- [ ] Add a nightly "run absolutely everything on develop and forward the results to the team" action.  This would provide low-cost coverage of all the items that might not have run during PR, and increase overall system confidence.
- [ ] Add retries in gradle (e.g.) [java conventions](https://github.com/hashgraph/hedera-mirror-node/blob/ef2826e3c4518b7e91e4afa16f2124bce0b0a314/buildSrc/src/main/kotlin/java-conventions.gradle.kts#L86) `maxRetries.set(3)` to less stable tests to give them a better chance to succeed.
- [ ] #7452

### Alternatives

Keep the status-quo and accept the time cost.
* Those costs include hours for each PR, and as more engineers join the team will grow in cost geometrically.
* The cost is tolerable, just, for now, but some level of improvement will be needed soon.
