### ISSUE TITLE
Improvements: Modularization & Dependencies

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#7148]
TODO: Description of epic

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/5162
- [ ] https://github.com/hashgraph/hedera-services/issues/5187
- [ ] https://github.com/hashgraph/hedera-services/issues/5240
- [ ] https://github.com/hashgraph/hedera-services/issues/5264
- [ ] https://github.com/hashgraph/hedera-services/issues/5271
- [ ] https://github.com/hashgraph/hedera-services/issues/5275
- [ ] https://github.com/hashgraph/hedera-services/issues/5293
- [ ] https://github.com/hashgraph/hedera-services/issues/5681
- [ ] https://github.com/hashgraph/hedera-services/issues/5815
- [ ] https://github.com/hashgraph/hedera-services/issues/5845
- [ ] https://github.com/hashgraph/hedera-services/issues/5846
- [ ] https://github.com/hashgraph/hedera-services/issues/5847
- [ ] https://github.com/hashgraph/hedera-services/issues/5970
- [ ] https://github.com/hashgraph/hedera-services/issues/5975
- [ ] https://github.com/hashgraph/hedera-services/issues/5979
- [ ] https://github.com/hashgraph/hedera-services/issues/6030
- [ ] https://github.com/hashgraph/hedera-services/issues/6611
- [ ] https://github.com/hashgraph/hedera-services/issues/6612
- [ ] https://github.com/hashgraph/hedera-services/issues/6613
- [ ] https://github.com/hashgraph/hedera-services/issues/6614
- [ ] https://github.com/hashgraph/hedera-services/issues/6615
- [ ] https://github.com/hashgraph/hedera-services/issues/6616
- [ ] https://github.com/hashgraph/hedera-services/issues/6617
- [ ] https://github.com/hashgraph/hedera-services/issues/6618
- [ ] https://github.com/hashgraph/hedera-services/issues/6619
- [ ] https://github.com/hashgraph/hedera-services/issues/6638
- [ ] https://github.com/hashgraph/hedera-services/issues/6639
- [ ] https://github.com/hashgraph/hedera-services/issues/6640
- [ ] https://github.com/hashgraph/hedera-services/issues/6641
- [ ] https://github.com/hashgraph/hedera-services/issues/6645
- [ ] https://github.com/hashgraph/hedera-services/issues/6648
- [ ] https://github.com/hashgraph/hedera-services/issues/6649
- [ ] https://github.com/hashgraph/hedera-services/issues/7151
- [ ] https://github.com/hashgraph/hedera-services/issues/7164
- [ ] https://github.com/hashgraph/hedera-services/issues/7165
- [ ] https://github.com/hashgraph/hedera-services/issues/7166
- [ ] https://github.com/hashgraph/hedera-services/issues/7167
- [ ] https://github.com/hashgraph/hedera-services/issues/7168
- [ ] https://github.com/hashgraph/hedera-services/issues/7169
- [ ] https://github.com/hashgraph/hedera-services/issues/7170
- [ ] https://github.com/hashgraph/hedera-services/issues/7654
- [ ] https://github.com/hashgraph/hedera-services/issues/9705
- [ ] https://github.com/hashgraph/hedera-services/issues/9784
- [ ] https://github.com/hashgraph/hedera-services/issues/8071
- [ ] https://github.com/hashgraph/hedera-services/issues/9785
- [ ] https://github.com/hashgraph/hedera-services/issues/9786
- [ ] https://github.com/hashgraph/hedera-services/issues/9788
- [ ] https://github.com/hashgraph/hedera-services/issues/9790
- [ ] https://github.com/hashgraph/hedera-services/issues/9852
- [ ] https://github.com/hashgraph/hedera-services/issues/9878
```
1234

**Comment by poulok** [comment]
closing because we decided not to use an epic to track generic "improvements"
