### ISSUE TITLE
State Validation Tool - further improvements

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#7152]
### Problem

This is a follow up epic about possible improvement of the State Validation Tool covered by #5442 

### Solution

```[tasklist]
### Tasks
- [ ] #5539
- [ ] #5983
- [ ] #6021
- [ ] #6022
- [ ] #6023
- [ ] #8343
- [ ] https://github.com/hashgraph/hedera-services/issues/9387
- [ ] https://github.com/hashgraph/hedera-services/issues/9546
- [ ] https://github.com/hashgraph/hedera-services/issues/9561
- [ ] https://github.com/hashgraph/hedera-services/issues/9859
```
