### ISSUE TITLE
False Logging Warnings from new Properties

### ISSUE THREAD

**Issue by timo0** [hashgraph/hedera-services#7172]
Following our recent improvements to the metrics logging, there is still a persisting issue with some warnings that continue to be logged. This seems to be due to configurations that were added only to the new framework and were never integrated into Settings in the first place.

To completely eliminate these unnecessary warnings, we need to take the following steps:

```[tasklist]
### Tasks
- [ ] Remove Warning Logic from Settings.java
- [ ] Incorporate Old Settings into the New Framework
- [ ] Add Warning Logic to the New Configuration Engine
```
