### ISSUE TITLE
JRS Test Evaluation

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#7175]
The current set of JRS tests have not been reviewed in their entirety for a long time. There may be tests that are no longer needed or are duplicated by other tests. The goal is to remove any unnecessary or duplicative tests so that the remaining set are the ones we want and need.

```[tasklist]
### Tasks
- [ ] #7176
- [ ] Describe what each test is testing (what is the purpose of the test, and what feature set is being exercised)
- [ ] Create a list of tests to delete, and a list of any that should be added or modified
- [ ] Audit/iterate over list of test modifications and get consensus on it
- [ ] Implement changes
```
