### ISSUE TITLE
Update services to use the new fee facility API

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#7931]
```[tasklist]
### Tasks
- [x] Add Fee Computation to Util Service
- [ ] https://github.com/hashgraph/hedera-services/issues/7932
- [ ] https://github.com/hashgraph/hedera-services/issues/8683
- [ ] https://github.com/hashgraph/hedera-services/issues/8971
- [x] Add Fee Computation to File Service
- [x] Add Fee Computation to Token Service
- [x] Add Fee Computation to Smart Contract Service
- [ ] https://github.com/hashgraph/hedera-services/issues/9054
```
