### ISSUE TITLE
0.42 Release Tasks

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#8064]
- [x] #8176
- [x] Create `v0.42.0-alpha.0` tag from `develop` branch – 24 Aug 2023 (regular Thursday tag)
- [x] Make sure config changes from the 0.41 release make it into source code for release 0.42. 
- [x] #8239
- [x] Create `v0.42.0-alpha.1` tag from `develop` branch – 31 Aug (regular Thursday tag)
- [x] Create `v0.42.0-alpha.2` tag from `develop` branch – 31 Aug
        Needed to start longevity testing for data on disk
- [x] Deploy `v0.42.0-alpha.2` to previewnet via new workflow – 31 Aug (Workflow [here](https://github.com/hashgraph/hedera-services/actions/runs/6041125004/job/16393406025))
- [x] Cut `release/0.42` branch – 1 Sep
- [x] #8504 
- [x] Cherry-pick #8504 to `develop`. See also #8668 
- [x] Tag and deploy services `v0.42.0-alpha.3` – 11 Sep
- [x] Tagged `v0.42.0-alpha.4` and deployed to previewnet – 14 Sep
- [x] Tagged release candidate `v0.42.0` and deployed to previewnet – 15 Sep
- [x] Tag and release `v0.42.0` protobufs – tag [here](https://github.com/hashgraph/hedera-protobufs/releases/tag/v0.42.0)
- [x] Tag and release `v0.42.0` _Java_ protobufs – tag [here](https://github.com/hashgraph/hedera-protobufs-java/releases/tag/v0.42.0)
- [x] Tag services release candidate `v0.42.1` – 21 Sep
- [x] Re-add mainnet `bootstrap.properties` file to `develop` – #8914 
- [x] Re-add mainnet `bootstrap.properties` file to `release/0.42` – #8928 
- [x] Tag services release candidate `v0.42.2` – 29 Sep
- [x] Add release notes to v0.42.0, 42.1, and 42.2 – 2 Oct
- [x] Add file 150 changes from #8986 – #9010 
- [x] Tag services release candidate v0.42.3 – 3 Oct
- [x] Add release notes to v0.42.3 – 27 Oct
- [x] Update repo properties with file contents from mainnet and testnet (develop) – #9055 
- [x] Update repo properties with file contents from mainnet and testnet (release/0.42) – #9077 
- [x] #9158 
- [x] Tag services release candidate `v0.42.4` – 11 Oct
- [x] Fix bad properties in testnet configs – #9208, #9209, #9210
- [x] Tag services release candidate `v0.42.5` – 11 Oct
- [x] Upgrade platform SDK dependency from `0.42.0` to `0.42.6` – #9224 
- [x] Tag services release candidate `v0.42.6` – 12 Oct

**Comment by mhess-swl** [comment]
0.42.6 deployed to mainnet on 24 Oct
