### ISSUE TITLE
Start testing `TokenCreateSpecs`

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#8077]
- [ ] validateNewTokenAssociations(will be fixed in https://github.com/hashgraph/hedera-services/issues/8757)
- [x] createsFungibleInfiniteByDefault
- [x] worksAsExpectedWithDefaultTokenId
- [x] cannotCreateWithExcessiveLifetime
- [ ] autoRenewValidationWorks(will be fixed in https://github.com/hashgraph/hedera-services/issues/8758)
- [x] creationYieldsExpectedToken
- [x] creationSetsExpectedName
- [x] creationWithoutKYCSetsCorrectStatus
- [ ] baseCreationsHaveExpectedPrices(will be fixed in https://github.com/hashgraph/hedera-services/issues/8808)
- [x] creationHappyPath
- [x] creationSetsCorrectExpiry
- [x] creationValidatesExpiry
- [x] creationValidatesFreezeDefaultWithNoFreezeKey
- [x] creationValidatesMemo
- [x] creationValidatesNonFungiblePrechecks
- [x] creationValidatesMaxSupply
- [ ] onlyValidCustomFeeScheduleCanBeCreated(will be fixed in https://github.com/hashgraph/hedera-services/issues/8811)
- [x] feeCollectorSigningReqsWorkForTokenCreate
- [x] creationValidatesName
- [x] creationValidatesSymbol
- [x] creationRequiresAppropriateSigs
- [x] creationRequiresAppropriateSigsHappyPath
- [x] creationValidatesTreasuryAccount
- [x] initialSupplyMustBeSane
- [x] treasuryHasCorrectBalance
- [x] prechecksWork
