### ISSUE TITLE
EPIC: Implement HIP-756

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#8085]
### Problem

HIP-756 has which allows parties to sign scheduled transactions to assign themselves to roles such as autoRenew and treasury for tokens has not been implemented.

This has a dependency on HIP 755 completion

### Solution

Implement HIP-756.  Some of the necessary tasks include

```[tasklist]
### HIP 756 Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/10731
- [ ] https://github.com/hashgraph/hedera-services/issues/16837
- [ ] https://github.com/hashgraph/hedera-services/issues/16963
- [ ] https://github.com/hashgraph/hedera-services/issues/16967
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1193
- [ ] https://github.com/hashgraph/hedera-services/issues/16964
- [ ] https://github.com/hashgraph/hedera-services/issues/17464
- [ ] https://github.com/hashgraph/hedera-services/issues/17428
```

**Comment by Nana-EC** [comment]
In 0.59.0 B the focus should mainly be closing off testing coverage.
Might even be worth trying a custom build in LocalNode to get early confidence

**Comment by lukelee-sl** [comment]
This epic has been completed
