### ISSUE TITLE
Implement HIP-632

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-services#8086]
### Problem

Hip-632 which implements the Hedera Account Services has not yet been created.

### Solution

Implement HIP-632 which involves the following tasks

- [ ] Create a formal design document based on design artifact found here https://www.notion.so/swirldslabs/HIP-632-Hedera-Account-Service-System-Contract-759967cd555940b58da36868247d3d9a
- [ ] Create a new Hedera account service precompile which handles two new function calls.
- [ ] The signature verification facility needs to be turned into a module.  Create a dependency from the smart contract module to the new signature verification module
- [ ] Create tests add need to validate functionality

**Comment by david-bakin-sl** [comment]
Closed in favor of #4619
