### ISSUE TITLE
Improve HTML swirlds logs

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#8296]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/8298
- [ ] https://github.com/hashgraph/hedera-services/issues/8299
- [ ] https://github.com/hashgraph/hedera-services/issues/8300
- [ ] https://github.com/hashgraph/hedera-services/issues/8301
- [ ] https://github.com/hashgraph/hedera-services/issues/8302
- [ ] https://github.com/hashgraph/hedera-services/issues/8303
- [ ] https://github.com/hashgraph/hedera-services/issues/8304
- [ ] https://github.com/hashgraph/hedera-services/issues/8306
- [ ] https://github.com/hashgraph/hedera-services/issues/8309
- [ ] https://github.com/hashgraph/hedera-services/issues/8333
- [ ] https://github.com/hashgraph/hedera-services/issues/8334
- [ ] https://github.com/hashgraph/hedera-services/issues/8610
- [ ] https://github.com/hashgraph/hedera-services/issues/8837
```

**Comment by alittley** [comment]
Mistakenly closed

**Comment by alittley** [comment]
Unlikely to be prioritized, so I'm closing this epic. Required improvements can be brainstormed if dev effort is ever focused here
