### ISSUE TITLE
Factor `HapiTestEngine` nodes into a classloader-scoped unit with distinct data and log directories

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#8349]
Launch each node used in `@HapiTestSuite` tests within a classloader, and give each their own data and log directories. Then support launching either 1 or 4 node networks.
```[tasklist]
### Tasks
- [ ] Launch `HapiTestSuite` tests using a node that is classloader isolated
- [ ] Create a new node per `HapiTestSuite`
- [ ] Support `HapiTestSuite` with the number of nodes that should be part of the test suite (1-4)
```

**Comment by rbair23** [comment]
I did not succeed in this case to use classloader isolation. The problem is that `ConstructableRegistry` thwarts any attempt at classloader isolation, by reaching out side whatever classloader it was created with, finding the system classloader, and establishing its own classloading lookup tree.

So I instead use some hacks -- stopping threads and invasive reflection -- to find and stop the platform so it can be restarted.
