### ISSUE TITLE
Run Token and Ethereum E2E Tests

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#8523]
### Problem

 Adapt the following E2E tests to run successfully:

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/8556
- [ ] https://github.com/hashgraph/hedera-services/issues/8557
- [ ] https://github.com/hashgraph/hedera-services/issues/8558
- [ ] https://github.com/hashgraph/hedera-services/issues/8559
- [ ] https://github.com/hashgraph/hedera-services/issues/8598
- [ ] https://github.com/hashgraph/hedera-services/issues/8599
- [ ] https://github.com/hashgraph/hedera-services/issues/8600
- [ ] https://github.com/hashgraph/hedera-services/issues/8601
- [ ] https://github.com/hashgraph/hedera-services/issues/8602
- [ ] https://github.com/hashgraph/hedera-services/issues/8673
- [ ] https://github.com/hashgraph/hedera-services/issues/8674
- [ ] https://github.com/hashgraph/hedera-services/issues/8675
```

### Solution

Run the following suites and fix any errors.

**Comment by georgi-l95** [comment]
All resolved
