### ISSUE TITLE
Run Hapi, Token and Opcode e2e tests

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#8524]
### Problem

Adapt the following E2E tests to run successfully:

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/8804
- [ ] https://github.com/hashgraph/hedera-services/issues/8852
- [ ] https://github.com/hashgraph/hedera-services/issues/8854
- [ ] https://github.com/hashgraph/hedera-services/issues/8862
- [ ] https://github.com/hashgraph/hedera-services/issues/8855
- [ ] https://github.com/hashgraph/hedera-services/issues/8865
- [ ] https://github.com/hashgraph/hedera-services/issues/8867
- [ ] https://github.com/hashgraph/hedera-services/issues/8868
- [ ] https://github.com/hashgraph/hedera-services/issues/8869
- [ ] https://github.com/hashgraph/hedera-services/issues/8848
- [ ] https://github.com/hashgraph/hedera-services/issues/8885
- [ ] https://github.com/hashgraph/hedera-services/issues/8886
- [ ] https://github.com/hashgraph/hedera-services/issues/8889
- [ ] https://github.com/hashgraph/hedera-services/issues/8894
- [ ] https://github.com/hashgraph/hedera-services/issues/8849
- [ ] https://github.com/hashgraph/hedera-services/issues/8722
- [ ] https://github.com/hashgraph/hedera-services/issues/8857
- [ ] https://github.com/hashgraph/hedera-services/issues/8637
- [ ] https://github.com/hashgraph/hedera-services/issues/8897
- [ ] https://github.com/hashgraph/hedera-services/issues/8910
- [ ] https://github.com/hashgraph/hedera-services/issues/8615
- [ ] https://github.com/hashgraph/hedera-services/issues/8077
- [ ] https://github.com/hashgraph/hedera-services/issues/8788
```

### Solution

Run the following suites and fix any errors.
