### ISSUE TITLE
Add miscellaneous missing functionality

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-services#8681]
### Problem

We need to cover missing logic in the modularized code, that is connected to precompile gas calculation, fee calculation related to signature verification and child records creation.

### Solution

Implement missing logic in the modularized code:

- [ ] Precompile gas pricing strategy
- [ ] Signature verification logic fees
- [ ] Creating records for system contracts

**Comment by IvanKavaldzhiev** [comment]
No longer applicable.
