### ISSUE TITLE
Resolve issues related to Contract tests

### ISSUE THREAD

**Issue by MiroslavGatsanoga** [hashgraph/hedera-services#8909]
### Problem

After some debugging of some of the Contract tests we created the following issues needed to be resolved:

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/8718
- [ ] https://github.com/hashgraph/hedera-services/issues/8719
- [ ] https://github.com/hashgraph/hedera-services/issues/8813
- [ ] https://github.com/hashgraph/hedera-services/issues/8717
- [ ] https://github.com/hashgraph/hedera-services/issues/8721
- [ ] https://github.com/hashgraph/hedera-services/issues/8899
- [ ] https://github.com/hashgraph/hedera-services/issues/9178
- [ ] https://github.com/hashgraph/hedera-services/issues/9177
- [ ] https://github.com/hashgraph/hedera-services/issues/8996
- [ ] https://github.com/hashgraph/hedera-services/issues/8623
- [ ] https://github.com/hashgraph/hedera-services/issues/9223
- [ ] https://github.com/hashgraph/hedera-services/issues/9244
- [ ] https://github.com/hashgraph/hedera-services/issues/9124
- [ ] https://github.com/hashgraph/hedera-services/issues/9394
- [ ] https://github.com/hashgraph/hedera-services/issues/9436
- [ ] https://github.com/hashgraph/hedera-services/issues/9437
- [ ] https://github.com/hashgraph/hedera-services/issues/9766
- [ ] https://github.com/hashgraph/hedera-services/issues/9654
```

### Solution

Fix the listed issues.
