### ISSUE TITLE
Dynamic Address Book Phase 2

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#9237]
```[tasklist]
### Tasks
- [x] #9637
- [x] #9638
- [x] #13150
- [x] #13265
- [x] #13466
- [x] #13471
- [x] #13472
- [x] #13473
- [x] #13474
- [x] #13476
- [ ] #13477
- [ ] #13670
- [ ] #13787
- [ ] #13790
- [ ] #13873
- [ ] #13899
- [ ] https://github.com/hashgraph/hedera-services/issues/13980
- [ ] #13981
- [ ] https://github.com/hashgraph/hedera-services/issues/14066
- [ ] #14070
- [ ] #14086
- [ ] #14242 
- [ ] #14329
- [ ] https://github.com/hashgraph/hedera-services/issues/14172
- [ ] #14328 
- [ ] #14346 
- [ ] #14450
- [ ] #14500 
- [ ] #13915
- [ ] #14603 
- [ ] #15021
- [ ] #15161 
- [ ] #15231
- [ ] #15255
- [ ] #15449
- [ ] #15455 
- [ ] #15466 
- [ ] #15557
- [ ] #15950 
- [ ] #15938
- [ ] #16200
- [ ] #16490 
- [ ] #16493
- [ ] #16583
- [ ] #16645 
```

**Comment by iwsimon** [comment]
All DAB tasks are completed for 0.56 release.
