### ISSUE TITLE
Conditional, supported records of internal `CONTRACT_CREATION`'s (including finalizations of existing hollow accounts as contracts via `CREATE2`).

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#9431]
Validate the below happy path scenarios:
 - [ ] A `CREATE1` record matches the corresponding mono-service record.
 - [ ] A `CREATE2` record matches the corresponding mono-service record.
 - [ ] A `CREATE2` hollow account completion as contract matches the corresponding mono-service record.

And the failure scenarios:
 - [ ] A `CREATE1` in the dynamic context of a reverted `MessageFrame` generates no record.
 - [ ] A `CREATE2` in the dynamic context of a reverted `MessageFrame` generates no record.
 - [ ] A `CREATE2` hollow account completion in the dynamic context of a reverted `MessageFrame` generates no record.

**Comment by JivkoKelchev** [comment]
Validated path scenarios:
	•	A CREATE1 record matches the corresponding mono-service record.
	CreateOperationSuite.simpleFactoryWorks()


	•	A CREATE2 record matches the corresponding mono-service record. 
	CreateOperationSuite.create2FactoryWorksAsExpected()


	•	A CREATE2 hollow account completion as contract matches the corresponding mono-service record.
	CreateOperationSuite.canMergeCreate2ChildWithHollowAccount() 


And the failure scenarios:
	•	A CREATE1 in the dynamic context of a reverted MessageFrame generates no record.
	CreateOperationSuite.resetOnFactoryFailureWorks()

	•	A CREATE2 in the dynamic context of a reverted MessageFrame generates no record.
	CreateOperationSuite.create2FactoryWorksAsExpected() This scenario first test failure, then success

	•	A CREATE2 hollow account completion in the dynamic context of a reverted MessageFrame generates no record.
	CreateOperationSuite.canMergeCreate2ChildWithHollowAccount() This scenario first test failure, then success

**All tests are passing, but still needs adjustment to pass FUZZY_MATCH_AGAINST_HAPI_TEST_STREAMS**



Validated child sidecars scenarios:

	•	A CREATE2 record matches the corresponding mono-service sidecars.
	TraceabilitySuite.traceabilityE2EScenario15() This scenario use CREATE2 DEPLOY

	•	A CREATE2 hollow account completion as contract matches the corresponding mono-service sidecars.
	TraceabilitySuite.hollowAccountCreate2MergeExportsExpectedSidecars()

**TODO:**
CREATE1 sidecar scenario
Reverted sidecars of all 3 scenarions
