### ISSUE TITLE
Event Refactor

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#9467]
Notes:

- the target event structure is documented [here](https://drive.google.com/file/d/1-KyGtwM-hF4LpiZzANxKD0T3y2u8T_LP/view?usp=drive_link)
- events cross upgrade boundaries, so while making changes we will need to be able to deserialize previous version events as well as being able to serialize them to the exact same bytes (this is needed to validate the hash of the event)
- a good way to manage this migration is to have separate fields for protobuf objects
- once the refactor is done, a SelfSerializable will wrap a protobuf event to support migration. once the migration is complete, we can remove that wrapper
- as far as we know, no one is consuming the consensus event stream, so making changes to it is not a problem
- due to current challenges, all protobuf definitions will be in the same module, platform and services

End goals:
- [ ] Apps consume all required protobuf records (payloads, core data, signature)
- [ ] Gossip (& PCES) protobuf events
- [ ] Double hash payloads when hashing an event
- [ ] Cleanup internal event structure

```[tasklist]
### Apps consume all required protobuf records
- [ ] https://github.com/hashgraph/hedera-services/issues/13861
- [ ] https://github.com/hashgraph/hedera-services/issues/13998
- [ ] https://github.com/hashgraph/hedera-services/issues/13999
- [ ] https://github.com/hashgraph/hedera-services/issues/14001
- [ ] https://github.com/hashgraph/hedera-services/issues/14000
- [ ] https://github.com/hashgraph/hedera-services/issues/14384
- [ ] https://github.com/hashgraph/hedera-services/issues/14425
- [ ] https://github.com/hashgraph/hedera-services/issues/14426
```

```[tasklist]
### Change event hashing
- [ ] https://github.com/hashgraph/hedera-services/issues/13432
- [ ] https://github.com/hashgraph/hedera-services/issues/14002
- [ ] https://github.com/hashgraph/hedera-services/issues/14003
- [ ] https://github.com/hashgraph/hedera-services/issues/14005
- [ ] https://github.com/hashgraph/hedera-services/issues/14006
- [ ] https://github.com/hashgraph/hedera-services/issues/14095
- [ ] https://github.com/hashgraph/hedera-services/issues/14259
- [ ] https://github.com/hashgraph/hedera-services/issues/14400
- [ ] https://github.com/hashgraph/hedera-services/issues/14386
- [ ] https://github.com/hashgraph/hedera-services/issues/14385
- [ ] https://github.com/hashgraph/hedera-services/issues/14442
- [ ] https://github.com/hashgraph/hedera-services/issues/14783
- [ ] https://github.com/hashgraph/hedera-services/issues/14942
- [ ] https://github.com/hashgraph/hedera-services/issues/14943
- [ ] https://github.com/hashgraph/hedera-services/issues/15102
```

```[tasklist]
### Cleanup internal event structure
- [ ] https://github.com/hashgraph/hedera-services/issues/13172
- [ ] https://github.com/hashgraph/hedera-services/issues/14004
- [ ] https://github.com/hashgraph/hedera-services/issues/13864
- [ ] https://github.com/hashgraph/hedera-services/issues/14007
- [ ] https://github.com/hashgraph/hedera-services/issues/14008
- [ ] https://github.com/hashgraph/hedera-services/issues/13138
- [ ] https://github.com/hashgraph/hedera-services/issues/14009
- [ ] https://github.com/hashgraph/hedera-services/issues/14010
- [ ] https://github.com/hashgraph/hedera-services/issues/14011
- [ ] https://github.com/hashgraph/hedera-services/issues/11389
- [ ] https://github.com/hashgraph/hedera-services/issues/14554
- [ ] https://github.com/hashgraph/hedera-services/issues/14555
- [ ] https://github.com/hashgraph/hedera-services/issues/14740
```

```[tasklist]
### Gossip & PCES protobuf events (after hashing)
- [ ] https://github.com/hashgraph/hedera-services/issues/14012
- [ ] https://github.com/hashgraph/hedera-services/issues/14935
- [ ] https://github.com/hashgraph/hedera-services/issues/15202
- [ ] https://github.com/hashgraph/hedera-services/issues/15205
- [ ] https://github.com/hashgraph/hedera-services/issues/15208
- [ ] https://github.com/hashgraph/hedera-services/issues/15284
```

```[tasklist]
### Things done
- [ ] https://github.com/hashgraph/hedera-services/issues/11387
- [ ] https://github.com/hashgraph/hedera-services/issues/11384
- [ ] https://github.com/hashgraph/hedera-services/issues/11383
- [ ] https://github.com/hashgraph/hedera-services/issues/11386
- [ ] https://github.com/hashgraph/hedera-services/issues/11388
- [x] Finalize protobuf plan
- [ ] https://github.com/hashgraph/hedera-services/issues/11764
- [ ] https://github.com/hashgraph/hedera-services/issues/11864
- [ ] https://github.com/hashgraph/hedera-services/issues/11862
- [ ] https://github.com/hashgraph/hedera-services/issues/12021
- [ ] https://github.com/hashgraph/hedera-services/issues/12210
- [ ] https://github.com/hashgraph/hedera-services/issues/12214
- [ ] https://github.com/hashgraph/hedera-services/issues/12331
- [ ] https://github.com/hashgraph/hedera-services/issues/12589
- [ ] https://github.com/hashgraph/hedera-services/issues/12292
- [ ] https://github.com/hashgraph/hedera-services/issues/12420
- [ ] https://github.com/hashgraph/hedera-services/issues/12551
- [ ] https://github.com/hashgraph/hedera-services/issues/12847
- [ ] https://github.com/hashgraph/hedera-services/issues/12850
- [ ] https://github.com/hashgraph/hedera-services/issues/12885
- [ ] https://github.com/hashgraph/hedera-services/issues/13399
- [ ] https://github.com/hashgraph/hedera-services/issues/13709
- [ ] https://github.com/hashgraph/hedera-services/issues/12473
- [ ] https://github.com/hashgraph/hedera-services/issues/12947
- [ ] https://github.com/hashgraph/hedera-services/issues/12982
- [ ] https://github.com/hashgraph/hedera-services/issues/12996
- [ ] https://github.com/hashgraph/hedera-services/issues/13238
- [ ] https://github.com/hashgraph/hedera-services/issues/13344
- [ ] https://github.com/hashgraph/hedera-services/issues/13308
- [ ] https://github.com/hashgraph/hedera-services/issues/13811
- [ ] https://github.com/hashgraph/hedera-services/issues/13015
- [ ] https://github.com/hashgraph/hedera-services/issues/13139
- [ ] https://github.com/hashgraph/hedera-services/issues/13000
- [ ] https://github.com/hashgraph/hedera-services/issues/12456
- [x] Remove Transaction.getContents()
- [ ] https://github.com/hashgraph/hedera-services/issues/13568
- [ ] https://github.com/hashgraph/hedera-services/issues/13760
- [ ] #13860
- [ ] #5224
- [ ] #11300
- [x] Delete `UnhashedEventData`
- [ ] https://github.com/hashgraph/hedera-services/issues/10978
- [ ] https://github.com/hashgraph/hedera-services/issues/12464
- [ ] https://github.com/hashgraph/hedera-services/issues/12898
- [ ] https://github.com/hashgraph/hedera-services/issues/12959
```
