### ISSUE TITLE
Coordinated Reconnect Abort

### ISSUE THREAD

**Issue by poulok** [hashgraph/hedera-services#9867]
This ticket is a follow up to address https://github.com/hashgraph/hedera-services/issues/9725 in a better way.

Reconnect needs a way to end in the middle of the protocol without data loss on the learner side. The teacher should then invoke this coordinate abort process if it detects that it is too close to falling behind.

```[tasklist]
### Tasks
- [ ] Implement coordinated reconnect abort
- [ ] Learner should not discard a partial state if reconnect is aborted
- [ ] Teacher should detect when it is close to falling behind while teaching
```
