### ISSUE TITLE
Componentize platform

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#9874]
### Intro
With the introduction of the new wiring framework, all the business logic in the platform needs to be put into components.

### Proposal
[Diagram](https://github.com/hashgraph/hedera-services/blob/05326-D-components-diagram/platform-sdk/docs/core/components-wip.svg)

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-services/issues/9448
- [ ] https://github.com/hashgraph/hedera-services/issues/9819
- [ ] https://github.com/hashgraph/hedera-services/issues/9683
- [ ] https://github.com/hashgraph/hedera-services/issues/9954
- [ ] https://github.com/hashgraph/hedera-services/issues/9999
- [ ] https://github.com/hashgraph/hedera-services/issues/10052
- [ ] https://github.com/hashgraph/hedera-services/issues/9998
- [ ] https://github.com/hashgraph/hedera-services/issues/9684
- [ ] https://github.com/hashgraph/hedera-services/issues/10504
- [ ] https://github.com/hashgraph/hedera-services/issues/10319
- [ ] https://github.com/hashgraph/hedera-services/issues/9715
- [ ] https://github.com/hashgraph/hedera-services/issues/9713
- [ ] https://github.com/hashgraph/hedera-services/issues/10024
- [ ] https://github.com/hashgraph/hedera-services/issues/10204
- [ ] https://github.com/hashgraph/hedera-services/issues/10222
- [ ] https://github.com/hashgraph/hedera-services/issues/10187
- [ ] https://github.com/hashgraph/hedera-services/issues/10815
- [ ] https://github.com/hashgraph/hedera-services/issues/10898
- [ ] https://github.com/hashgraph/hedera-services/issues/9746
- [ ] https://github.com/hashgraph/hedera-services/issues/10901
- [ ] https://github.com/hashgraph/hedera-services/issues/11307
- [ ] https://github.com/hashgraph/hedera-services/issues/10984
- [ ] https://github.com/hashgraph/hedera-services/issues/10000
- [ ] https://github.com/hashgraph/hedera-services/issues/10017
- [ ] https://github.com/hashgraph/hedera-services/issues/11446
- [ ] https://github.com/hashgraph/hedera-services/issues/10899
- [ ] https://github.com/hashgraph/hedera-services/issues/10900
- [ ] https://github.com/hashgraph/hedera-services/issues/11901
- [ ] https://github.com/hashgraph/hedera-services/issues/11987
- [ ] https://github.com/hashgraph/hedera-services/issues/11985
- [ ] https://github.com/hashgraph/hedera-services/issues/12034
- [ ] https://github.com/hashgraph/hedera-services/issues/10983
- [ ] https://github.com/hashgraph/hedera-services/issues/11280
- [ ] https://github.com/hashgraph/hedera-services/issues/11113
- [ ] https://github.com/hashgraph/hedera-services/issues/11716
- [ ] https://github.com/hashgraph/hedera-services/issues/11076
- [ ] Create consensus nexus
```
